### PR TITLE
[1.0-beta1] P2P: Fix stuck in peer syncing state

### LINKED ISSUE #150: Test failure: lib_advance_test
https://github.com/AntelopeIO/spring/actions/runs/9114438126/job/25059003107?pr=149

node_03 is stuck in lib catchup. Since blocks can be processed inside controller during a fork and don't call `sync_master->sync_recv_block` with `blk_applied==true`.

### PR DESCRIPTION
**Pull request by heifner**
Test failure: https://github.com/AntelopeIO/spring/actions/runs/9114438126/job/25059003107?pr=149

The producing node (Node03) was stuck in LIB catchup. Since blocks can be processed inside controller during a fork and not call `sync_master->sync_recv_block` with `blk_applied==true`. 

This is similar to the issue addressed in #27. In the #27, a handshake with the wrong information was sent. In this case no handshake was sent at all as it become synced up during a fork switch. I believe this issue was masked by #147 because it was incorrectly reporting blocks as applied. Without this improper reporting of applied blocks a fork switch that applies up to synced would not call  `sync_master->sync_recv_block` with `blk_applied==true` and not move node out of LIB catchup.

Now also send out handshakes if we determine we are synced and there is a pending handshake to send.

Related to #27 
Related to #147 

Resolves #150

### CODE REVIEW

File: plugins/net_plugin/net_plugin.cpp [hunk 1]
```diff
@@ -4007,7 +4018,8 @@ namespace eosio {
       });
    }
 
-   void net_plugin_impl::on_accepted_block() {
+   void net_plugin_impl::on_accepted_block( const signed_block_ptr& block, const block_id_type& id ) {
```
Comment (linh2931) [inline plugins/net_plugin/net_plugin.cpp:4021]: `id` is not used.

File: plugins/net_plugin/net_plugin.cpp [hunk 2]
```diff
@@ -4007,7 +4018,8 @@ namespace eosio {
...
+      sync_master->send_handshakes_if_synced(fc::time_point::now() - block->timestamp);
```
Comment (linh2931) [inline plugins/net_plugin/net_plugin.cpp:4022]: You can add an assert `now` is greater than `timestamp`.

Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp:4022]: We can not assume that `now()` is greater than `block->timestamp`.

**Review by spoonincode — APPROVED** [review]

File: plugins/net_plugin/net_plugin.cpp (hunk 2 above)
Comment (linh2931) [reply plugins/net_plugin/net_plugin.cpp:4022]: Oh I see `fc::microseconds` checks negative input.

**Review by linh2931 — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: BUG
summary: Add handshakes to cover additional P2P scenarios, including during a fork and when there are pending handshakes after a sync complete. 
Note:end
