### PR TITLE
[2.0.0-dev] Generate new snapshot on fork

### LINKED ISSUE #1489: Don't fail when fork during snapshot create
change /v1/producer/create_snapshot to work like a scheduled snapshot and automatically regenerate the snapshot on fork switch and continue to wait until the new snapshot is ready and return it.

### PR DESCRIPTION
**Pull request by heifner**
Instead of generating an error on `/v1/producer/create_snapshot` when the block is forked out, generate a new snapshot and report that snapshot to the user.

Example from fork test:
```
debug 2025-05-22T15:56:19.502 http-1    beast_http_session.hpp:157    handle_request       ] Request:  localhost:8889 POST /v1/producer/create_snapshot HTTP/1.1  Accept-Encoding: identity  Content-Length: 0  Host: localhost:8889  User-Agent: Python-urllib/3.10  Connection: close    
debug 2025-05-22T15:56:19.502 nodeos    snapshot_scheduler.cpp:16     operator()           ] snapshot scheduler creating a snapshot from the request [start_block_num:189, end_block_num=4294967295, block_spacing=0], height=190
info  2025-05-22T15:56:19.503 nodeos    snapshot_scheduler.cpp:219    create_snapshot      ] Starting snapshot creation at block 189
info  2025-05-22T15:56:19.509 nodeos    snapshot_scheduler.cpp:228    create_snapshot      ] Snapshot creation at block 189 complete; snapshot will be available once block 000000bdc5b795aee58a5bcd281c44fe58c91f2a905eaafc6df756af63b6be66 becomes irreversible
debug 2025-05-22T15:56:23.063 nodeos    snapshot_scheduler.cpp:16     operator()           ] snapshot scheduler creating a snapshot from the request [start_block_num:189, end_block_num=4294967295, block_spacing=0], height=190
info  2025-05-22T15:56:23.063 nodeos    snapshot_scheduler.cpp:219    create_snapshot      ] Starting snapshot creation at block 189
info  2025-05-22T15:56:23.069 nodeos    snapshot_scheduler.cpp:228    create_snapshot      ] Snapshot creation at block 189 complete; snapshot will be available once block 000000bdf1cb0972dcf8164828df59f1b320d239d2ac9faaad33526caf7bdad9 becomes irreversible
info  2025-05-22T15:56:47.970 nodeos    pending_snapshot.hpp:57       finalize             ] Snapshot created at block 189 id 000000bdc5b795aee58a5bcd281c44fe58c91f2a905eaafc6df756af63b6be66 invalidated because block was forked out
warn  2025-05-22T15:56:47.970 nodeos    snapshot_scheduler.cpp:45     on_irreversible_bloc ] 3170009 snapshot_finalization_exception: Snapshot Finalization Exception
Snapshot block 189 was forked out of the chain. ID: 000000bdc5b795aee58a5bcd281c44fe58c91f2a905eaafc6df756af63b6be66
    nodeos  pending_snapshot.hpp:59 finalize
info  2025-05-22T15:56:47.970 nodeos    pending_snapshot.hpp:67       finalize             ] Snapshot created at block 189 available at /home/heifner/ext/leap/cmake-build-debug/TestLogs/nodeos_snapshot_forked_test83768/node_01/snapshots/snapshot-000000bdf1cb0972dcf8164828df59f1b320d239d2ac9faaad33526caf7bdad9.bin
debug 2025-05-22T15:56:47.970 http-0    beast_http_session.hpp:481    send_response        ] Response: localhost:8889 HTTP/1.1 201 Created  Connection: close  Server: nodeos/v2.0.0-dev  Content-Type: application/json  Content-Length: 358    {"head_block_id":"000000bdf1cb0972dcf8164828df59f1b320d239d2ac9faaad33526caf7bdad9","head_block_num":189,"head_block_time":"2025-05-22T15:56:08.000","version":8,"snapshot_name":"/home/heifner/ext/leap/cmake-build-debug/TestLogs/nodeos_snapshot_forked_test83768/node_01/snapshots/snapshot-000000bdf1cb0972dcf8164828df59f1b320d239d2ac9faaad33526caf7bdad9.bin"}
```

Resolves #1489

### CODE REVIEW

File: libraries/chain/snapshot_scheduler.cpp [hunk 1]
```diff
@@ -203,13 +211,7 @@ void snapshot_scheduler::create_snapshot(next_function<snapshot_information> nex
    auto& pending_by_id = _pending_snapshot_index.get<by_id>();
    auto existing = pending_by_id.find(head_id);
    if(existing != pending_by_id.end()) {
```
Comment (linh2931) [inline libraries/chain/snapshot_scheduler.cpp:213]: Why not change the if condition to `if(existing == pending_by_id.end()) {` to avoid an empty `if` clause?

File: libraries/chain/snapshot_scheduler.cpp [hunk 2]
```diff
@@ -131,11 +136,14 @@ void snapshot_scheduler::add_pending_snapshot_info(const snapshot_information& s
    }
 }
 
-void snapshot_scheduler::execute_snapshot(uint32_t srid, chain::controller& chain) {
+void snapshot_scheduler::execute_snapshot(uint32_t srid, chain::controller& chain, next_function<snapshot_information> http_next) {
    _inflight_sid = srid;
-   auto next = [srid, this](const chain::next_function_variant<snapshot_information>& result) {
+   auto next = [srid, this, http_next](const chain::next_function_variant<snapshot_information>& result) {
+      if (http_next)
+         http_next(result);
```
[the remark this answers is not in the document]
Comment (heifner) [reply libraries/chain/snapshot_scheduler.cpp:143]: `http_next` also reports success, it needs to be called in either case.

File: libraries/chain/snapshot_scheduler.cpp (hunk 1 above)
Comment (heifner) [reply libraries/chain/snapshot_scheduler.cpp]: https://github.com/AntelopeIO/spring/pull/1538/commits/bf0c467da6f5294340cdf8ffd4323aa3f3d29f3d

**Review by linh2931 — APPROVED** [review]
