### PR TITLE
[1.0-beta1.1] Store proposed producers and proposed finalizers in building block

### LINKED ISSUE #182: Nodeos Crashes after actfinkey action
There are 3 nodeos processes each with a different registered block producer. Setup in a private network running Savanna consensus. Steps to reproduce 
- create a new 4th BLS key via spring-utils
- add key to config as `signature-provided`
- restart nodeos for one producer 
- register new key with producer name
- activate newly registered  key 

[bt_all_threads.txt](https://github.com/AntelopeIO/spring/files/15393788/bt_all_threads.txt)

```
nodeos --full-version
info  2024-05-21T18:08:14.494 nodeos    main.cpp:151                  main                 ] nodeos started
v1.0.0-dev-2187c808682a05270025a4de751e6c16667a0274
```

reference-contracts commit `cd645b54a176f0c8b5f2f5ea9b21f47b7f9bf7eb` using `system-contract`

Commands Used
```
# register key 
cleos --url $ENDPOINT push action eosio regfinkey "{\"finalizer_name\":\"${producer_name:?}\", \
                            \"finalizer_key\":\"${PUBLIC_KEY:?}\", \
                            \"proof_of_possession\":\"${PROOF_POSSESION:?}\"}" -p ${producer_name:?}

# send actkey action
cleos --url $ENDPOINT push action eosio actfinkey "{\"finalizer_name\":\"${producer_name:?}\", \
                            \"finalizer_key\":\"${PUBLIC_KEY:?}\"}" -p ${producer_name:?}
```

Table output before called `actfinkey`
```
enfuser@6045285f2fdd:/local/eosnetworkfoundation/repos/bootstrap-private-network/bin$ cleos --url $ENDPOINT get table eosio eosio finalizers
{
  "rows": [{
      "finalizer_name": "bpa",
      "active_key_id": 0,
      "active_key_binary": "1f3758885c8eb448340fee9e2e256e6d58f53a7f701f404b3f4619e9d04fc15504c39477bebf711cf219fb0376ea2716fa4641278192af68a6675a2ab853326d85d985dfa3098e813e70b08b3ff5eb665ece1acf42d92b89b7a86807e6eb4512",
      "finalizer_key_count": 1
    },{
      "finalizer_name": "bpb",
      "active_key_id": 1,
      "active_key_binary": "b3064e0e296d2d7c3dd65517ae11a6333abd54deb2ab630bac61b82f2f9039b7e781d19105d9e4d23d3842e068e42e14a5c10857114f22f66641f187d5231f2f1553ebb7381d163a558a4636898dc6541c304e3892b3576f53579146d3af9302",
      "finalizer_key_count": 2
    },{
      "finalizer_name": "bpc",
      "active_key_id": 2,
      "active_key_binary": "83b3c92a076c2c9edc28838a5b840d65e58ea38fd05b55313e85751348433280d996fd55b75d43374022bca025d0c4190311705aa37d8f020d614a1fed7153b0e89a1cbb9e47e8637f1154ed2c478725e10c2d50426b3a02db80bb30ae522a13",
      "finalizer_key_count": 1
    }
  ],
  "more": false,
  "next_key": ""
}
enfuser@6045285f2fdd:/local/eosnetworkfoundation/repos/bootstrap-private-network/bin$ cleos --url $ENDPOINT get table eosio eosio finkeys
{
  "rows": [{
      "id": 0,
      "finalizer_name": "bpa",
      "finalizer_key": "PUB_BLS_HzdYiFyOtEg0D-6eLiVubVj1On9wH0BLP0YZ6dBPwVUEw5R3vr9xHPIZ-wN26icW-kZBJ4GSr2imZ1oquFMybYXZhd-jCY6BPnCwiz_162ZezhrPQtkribeoaAfm60USeSFQMg",
      "finalizer_key_binary": "1f3758885c8eb448340fee9e2e256e6d58f53a7f701f404b3f4619e9d04fc15504c39477bebf711cf219fb0376ea2716fa4641278192af68a6675a2ab853326d85d985dfa3098e813e70b08b3ff5eb665ece1acf42d92b89b7a86807e6eb4512"
    },{
      "id": 1,
      "finalizer_name": "bpb",
      "finalizer_key": "PUB_BLS_swZODiltLXw91lUXrhGmMzq9VN6yq2MLrGG4Ly-QObfngdGRBdnk0j04QuBo5C4UpcEIVxFPIvZmQfGH1SMfLxVT67c4HRY6VYpGNomNxlQcME44krNXb1NXkUbTr5MC65Ktqg",
      "finalizer_key_binary": "b3064e0e296d2d7c3dd65517ae11a6333abd54deb2ab630bac61b82f2f9039b7e781d19105d9e4d23d3842e068e42e14a5c10857114f22f66641f187d5231f2f1553ebb7381d163a558a4636898dc6541c304e3892b3576f53579146d3af9302"
    },{
      "id": 2,
      "finalizer_name": "bpc",
      "finalizer_key": "PUB_BLS_g7PJKgdsLJ7cKIOKW4QNZeWOo4_QW1UxPoV1E0hDMoDZlv1Vt11DN0AivKAl0MQZAxFwWqN9jwINYUof7XFTsOiaHLueR-hjfxFU7SxHhyXhDC1QQms6AtuAuzCuUioTb4wE_w",
      "finalizer_key_binary": "83b3c92a076c2c9edc28838a5b840d65e58ea38fd05b55313e85751348433280d996fd55b75d43374022bca025d0c4190311705aa37d8f020d614a1fed7153b0e89a1cbb9e47e8637f1154ed2c478725e10c2d50426b3a02db80bb30ae522a13"
    },{
      "id": 3,
      "finalizer_name": "bpb",
      "finalizer_key": "PUB_BLS_jU4vH-DERn5BJEkNU6y1iGLjcJhcyp1I77TENbfbqP18K7sRaCSl272nHebpJG4MkfteRzZ2TLpnhrN7RpX-rTukejyHIBNT6lqjzE_nNa1hwjZKw49t5GQXaA4nkzkJ-lhVeA",
      "finalizer_key_binary": "8d4e2f1fe0c4467e4124490d53acb58862e370985cca9d48efb4c435b7dba8fd7c2bbb116824a5dbbda71de6e9246e0c91fb5e4736764cba6786b37b4695fead3ba47a3c87201353ea5aa3cc4fe735ad61c2364ac38f6de46417680e27933909"
    }
  ],
  "more": false,
  "next_key": ""
}
```

### PR DESCRIPTION
**Pull request by heifner**
The chainbase `global_property_object` was used to store `finalizer_policy` during block construction as a means to provide automatic rollback if the transaction/block failed. See https://github.com/AntelopeIO/spring/pull/99. However, `finalizer_policy` contains non-shared types of `std::vector` and `fc::crypto::blslib::bls_public_key`. 

This PR solves the problem of avoiding side-effects of proposed finalizer policy made in an aborted transaction in a different way than committing the speculative changes into the `global_property_object` in `chainbase`. Now we store the speculative changes in the transaction context. Then if we commit the transaction, it copies them over (assuming they are not nullopt) from the transaction context to the building block. This avoids having to add a shared version of the `finalizer_policy` and `bls_public_key`. 

For symmetry, the proposer schedule in Savanna was modified to also be managed the same way as `finalier_policy` in `transaction_context`.

This PR removes  `proposed_fin_pol_block_num` and `proposed_fin_pol` from `global_property_object` and therefore is not state compatible with previous versions. The proposed schedule `proposed_schedule_block_num` & `proposed_schedule` were not removed from `global_property_object` because they are still needed pre-Savanna.

Note PR #188 targets `main`. `main` includes producer and finalizer diffs. This is a cherry-pick of #188 with additional changes to fix merge conflicts.

Resolves #182

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]

**Review by spoonincode — APPROVED** [review]

File: libraries/chain/transaction_context.cpp [hunk 1]
```diff
@@ -831,5 +831,23 @@ namespace eosio::chain {
...
+         return -1; // INSTANT_FINALITY depends on DISALLOW_EMPTY_PRODUCER_SCHEDULE
+
+      EOS_ASSERT(producers.size() <= config::max_producers, wasm_execution_error,
+                 "Producer schedule exceeds the maximum proposer count for this chain");
+
+      trx_blk_context.proposed_schedule_block_num = control.head_block_num() + 1;
+      // proposed_schedule.version is set in assemble_block
+      trx_blk_context.proposed_schedule.producers = std::move(producers);
+
+      return std::numeric_limits<uint32_t>::max();
```
Comment (spoonincode) [inline libraries/chain/transaction_context.cpp:845]: Is this meant to be a `uint32_t` instead of `int64_t`? I realize that's how it was before this PR but the types being mismatched here looks sus

Comment (heifner) [reply libraries/chain/transaction_context.cpp:845]: Yes, that is in accordance to what @arhag requested. https://github.com/AntelopeIO/spring/blob/8ac62810950d7f28835d0a3e7a3bd75f58e5dec4/libraries/chain/include/eosio/chain/webassembly/interface.hpp#L156-L156

**Review by spoonincode — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: BUG
summary: Improve data safety for transaction rollback and avoid unintended side effects for a proposed finalizer policy change during an aborted transaction.
Note:end

**Comment by ericpassmore** [comment]
Validated this is working 
```
info  2024-05-23T19:46:59.964 nodeos    controller.cpp:1363           transition_to_savann ] Transitioning to savanna, IF Genesis Block 641, IF Critical Block 686
info  2024-05-23T19:46:59.964 nodeos    controller.cpp:1384           operator()           ] Transition to instant finality happening after block 686, First IF Proper Block 687
info  2024-05-23T19:52:24.899 nodeos    block_header_state.cpp:187    finish_next          ] New finalizer policy becoming active in block 0000052ce7505b324970d137ae0aff7a717ba812eb8c6000abecb0bbc593aea6: {"generation":2,"threshold":3,"finalizers":[{"description":"bpa","weight":1,"public_key":"PUB_BLS_n9zAW7r9sx6FvjDb_9e64ozf4MPXdO62LWkxtjZWkK-e5K_jvpJa0ugv8sy87UoUzt4I_FldyNnmFCv7wBdIAEAQHbHeiYz-izo2iaA9XAAufT4375SClQ8XUJAScjsRX9pUgw"},{"description":"bpc","weight":1,"public_key":"PUB_BLS_P38d0wxZuM668D6BHCdBOw5jjlhuVXqa6i7t7Hfa6CAY4GcoM6u8ruIYs7oKulMKz2cnJtEyuABM564mbRpXMvUd_stxJoOSyt_FHzea4I07vnMPrIlSPX1pYXffS-AS5tfITg"},{"description":"bpb","weight":1,"public_key":"PUB_BLS_RoazjGvyIFc9Jc7JSB7TTIJAKgPj43cabIgJ5PHj2zQP0pMfyzzQIR_JaMNTJ6YWaPNBqbUCgxtFoF-dd0Yjfxpp49faH-8ZgjcSF86K4AqMopl4k0juxE3x0QJCwVcDuVbrbw"}]}
```
