### PR TITLE
[1.1.0] Fix deferred trx processing

### LINKED ISSUE #1145: Spring 1.1 Misc Errors During Replay
Getting misc errors during replay test. Found in 
- run 20
   - job 140547858842528
   - start block 16150309
   - end block 17323276
- run 54
   - job 140547858857456
   - start block 46911265
   - end block 48116875

[nodeos140547858857456.log](https://github.com/user-attachments/files/18675035/nodeos140547858857456.log)
[nodeos140547858842528.log](https://github.com/user-attachments/files/18675033/nodeos140547858842528.log)

```
error 2025-02-05T14:21:39.934 nodeos    controller.cpp:3883           apply_block          ] e.to_detail_string(): 3100000 misc_exception: Miscellaneous exception
Setting a platform_timer callback when one already exists
    {}
    nodeos  platform_timer.hpp:36 set_expiration_callback
eosluckydice <= eosio::onerror pending console output: 
    {"console":"","account":"eosio","action":"onerror","receiver":"eosluckydice"}
    nodeos  apply_context.cpp:134 exec_one
 
warn  2025-02-05T14:21:39.934 nodeos    controller.cpp:4361           replay_irreversible_ ] 3100000 misc_exception: Miscellaneous exception
Setting a platform_timer callback when one already exists
    {}
    nodeos  platform_timer.hpp:36 set_expiration_callback
eosluckydice <= eosio::onerror pending console output: 
    {"console":"","account":"eosio","action":"onerror","receiver":"eosluckydice"}
    nodeos  apply_context.cpp:134 exec_one

    {}
    nodeos  controller.cpp:3891 apply_block

info  2025-02-05T14:21:39.934 nodeos    main.cpp:165                  operator()           ] nodeos version v1.1.0-rc1 v1.1.0-rc1-dcb9cc9bec4c175d38a03efedf2b50431ea35c71
```

### PR DESCRIPTION
**Pull request by heifner**
Currently with #1027 a long running trx is interrupted when the oc compile completes. This causes an issue with deferred trx processing in old blocks where deferred trxs exist. Disable interrupt of transaction when oc compile completes for implicit transactions. Implicit transactions include deferred `onerror` and `onblock`. Not interrupting `onblock` seems like an ok thing here as `onblock` is part of the main system contract.

Also stop() timer on oc interrupt so start() is always called on a stopped timer.
Also call `checktime()` after setup of cleanup in eos-vm-oc so that `set_expiration_callback(nullptr, nullptr);` is called on `checktime` exception.

chicken-dance mismatch still on this branch which is being tracked by https://github.com/AntelopeIO/spring/issues/1152

Resolves #1145

### CODE REVIEW

File: libraries/chain/controller.cpp [hunk 1]
```diff
@@ -2644,7 +2644,8 @@ struct controller_impl {
 
       transaction_checktime_timer trx_timer(timer);
       const packed_transaction trx( std::move( etrx ) );
-      transaction_context trx_context( self, trx, trx.id(), std::move(trx_timer), bb.action_receipt_digests().store_which(), start );
+      transaction_context trx_context( self, trx, trx.id(), std::move(trx_timer), bb.action_receipt_digests().store_which(),
+                                       start, transaction_metadata::trx_type::implicit );
```
Comment (linh2931) [inline libraries/chain/controller.cpp:2648]: onblock is implicit. But I don't see it see anywhere.

Comment (heifner) [reply libraries/chain/controller.cpp:2648]: https://github.com/AntelopeIO/spring/blob/f0d379a83309387d4e64e000823c928e20257396/libraries/chain/controller.cpp#L3031-L3031

It is set via `trx->get_trx_type()`.

File: libraries/chain/include/eosio/chain/wasm_interface_private.hpp [hunk 2]
```diff
@@ -164,7 +164,11 @@ struct eosvmoc_tier {
             }
          }
 #endif
-         const bool allow_oc_interrupt = attempt_tierup && context.is_applying_block() && context.trx_context.has_undo();
+         // do not allow oc interrupt if no undo as the transaction needs to be undone to restart it.
+         // do not allow oc interrupt if implicit as deferred trx onerror execute as implicit outside the transaction
+         // retry in transaction_context. Also scheduled manage the undo stack explicitly.
+         const bool allow_oc_interrupt = attempt_tierup && context.is_applying_block() &&
+                                         context.trx_context.has_undo() && !context.trx_context.is_implicit() && !context.trx_context.is_scheduled();
```
Comment (linh2931) [inline libraries/chain/include/eosio/chain/wasm_interface_private.hpp:171]: Do we need both `!context.trx_context.is_implicit()` and `!context.trx_context.is_scheduled()`? Is `!context.trx_context.is_scheduled()` sufficient?

File: libraries/chain/include/eosio/chain/wasm_interface_private.hpp [hunk 3]
```diff
@@ -164,7 +164,11 @@ struct eosvmoc_tier {
             }
          }
 #endif
-         const bool allow_oc_interrupt = attempt_tierup && context.is_applying_block() && context.trx_context.has_undo();
+         // do not allow oc interrupt if no undo as the transaction needs to be undone to restart it.
+         // do not allow oc interrupt if implicit as deferred trx onerror execute as implicit outside the transaction
```
Comment (linh2931) [inline libraries/chain/include/eosio/chain/wasm_interface_private.hpp:168]: This wording `if implicit as deferred trx` is a little confusing. Implicit trx and deferred trx are different.

**Comment by spoonincode** [comment]
Can you describe a call path that yielded the failure a little more? Because,
> Also call checktime() after setup of cleanup in eos-vm-oc so that set_expiration_callback(nullptr, nullptr); is called on checktime exception.

Couldn't this on its own have been a problem in prior releases?

**Comment by heifner** [comment]
> Can you describe a call path that yielded the failure a little more? Because,
> 
> > Also call checktime() after setup of cleanup in eos-vm-oc so that set_expiration_callback(nullptr, nullptr); is called on checktime exception.
> 
> Couldn't this on its own have been a problem in prior releases?

This has been this way since 2.0.0. I noticed it during visual inspection of all calls to `set_expiration_callback`. Certainly seems like this could have been an issue at any point. Maybe there was something that prevent(ed) checktime from ever being triggered there.

File: libraries/chain/include/eosio/chain/wasm_interface_private.hpp (hunk 3 above)
Comment (heifner) [reply libraries/chain/include/eosio/chain/wasm_interface_private.hpp]: I reworked the comment. https://github.com/AntelopeIO/spring/pull/1150/commits/845576c52b8cabecf6b315dbc44988debd6b1924

**Review by linh2931 — APPROVED** [review]

**Comment by spoonincode** [comment]
Sorry I should have written those as 2 separate questions more clearly. Can you describe the (or a) flow that was causing the problem?

**Comment by heifner** [comment]
> Sorry I should have written those as 2 separate questions more clearly. Can you describe the (or a) flow that was causing the problem?

## onerror case

While applying a block a deferred transaction is processed. During the processing of the deferred transaction the action was interrupted via oc interrupt. This throws the `interrupt_oc_exception` transaction out of `apply` (line 191):

https://github.com/AntelopeIO/spring/blob/845576c52b8cabecf6b315dbc44988debd6b1924/libraries/chain/include/eosio/chain/wasm_interface_private.hpp#L185-L195

This `interrupt_oc_exception` is expected to be caught in `transaction_context`:
https://github.com/AntelopeIO/spring/blob/845576c52b8cabecf6b315dbc44988debd6b1924/libraries/chain/transaction_context.cpp#L371-L375

However, `onerror` calls `trx_context.execute_action` directly from the controller:
https://github.com/AntelopeIO/spring/blob/845576c52b8cabecf6b315dbc44988debd6b1924/libraries/chain/controller.cpp#L2673-L2673

Which means the `interrupt_oc_exception` would be caught here:
https://github.com/AntelopeIO/spring/blob/845576c52b8cabecf6b315dbc44988debd6b1924/libraries/chain/controller.cpp#L2693-L2693

This `interrupt_oc_exception` would cause the `onerror` to fail. But the failure is captured into a trace of the `onerror` (not thrown on out). This results in a `hard_fail` instead of a `soft_fail`. Also the trx_context is undone instead of squashed.

### deferred trx case

I'm not really sure why interrupting deferred trxs exec() would be a problem. I was thinking it was because it created its own undo_session. But it shouldn't when validating a block. I now don't see why interrupting a deferred trx would cause any issue. I does, because one of the runs had the not interrupt for implicit but do interrupt for scheduled and that chicken-dance failed with an invalid `soft_fail`.

File: libraries/chain/transaction_context.cpp [hunk 4]
```diff
@@ -59,6 +59,7 @@ namespace eosio::chain {
       undo();
       *trace = transaction_trace{}; // reset trace
       initialize();
+      transaction_timer.stop();
```
Comment (heifner) [inline libraries/chain/transaction_context.cpp:62]: This was not needed. The `undo()` call above calls `transaction_timer.stop()`. I can remove it, but having it here makes it more obvious that it is being called.

**Comment by ericpassmore** [comment]
Note:start
category: Other
component: Internal
summary: Fix deferred trx process to support replay-ability. 
Note:end
