### PR TITLE
P2P: Fix duplication connection logic

### LINKED ISSUE #1092: P2P: Duplicate connections
The de-duplication logic does not appear to be working.

Note this output from some performance testing:
```
error 2025-01-03T16:00:25.505 net-0     net_plugin.cpp:2749           operator()           ] ["localhost:9889:blk - e1c6399" - 26 127.0.0.1:58544] bcast block 113
error 2025-01-03T16:00:25.505 net-0     net_plugin.cpp:2749           operator()           ] ["localhost:9882:blk - 8bd6bc5" - 27 127.0.0.1:58558] bcast block 113
error 2025-01-03T16:00:25.505 net-0     net_plugin.cpp:2749           operator()           ] ["localhost:9890:blk - ed19614" - 28 127.0.0.1:58574] bcast block 113
error 2025-01-03T16:00:25.505 net-0     net_plugin.cpp:2749           operator()           ] ["localhost:9883:blk - f370be8" - 29 127.0.0.1:58590] bcast block 113
error 2025-01-03T16:00:25.505 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9898:blk - 63056a6" - 30 127.0.0.1:58598] bcast block 113
error 2025-01-03T16:00:25.505 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9891:blk - 7ac6fa8" - 32 127.0.0.1:58620] bcast block 113
error 2025-01-03T16:00:25.505 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9899:blk - 2700938" - 34 127.0.0.1:58636] bcast block 113
error 2025-01-03T16:00:25.505 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9877:blk - beff04a" - 35 127.0.0.1:58652] bcast block 113
error 2025-01-03T16:00:25.505 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9900:blk - a50ed92" - 38 127.0.0.1:58674] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9893:blk - d48054a" - 40 127.0.0.1:58686] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9879:blk - c086f7b" - 43 127.0.0.1:58412] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9894:blk - 6f35397" - 44 127.0.0.1:58416] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9887:blk - 85a259a" - 45 127.0.0.1:58422] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9895:blk - f29d382" - 47 127.0.0.1:58446] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9776:blk - 3c7c4a7" - 1 127.0.0.1:9776] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9876:blk - c84cc39" - 2 127.0.0.1:9876] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9877:blk - beff04a" - 3 127.0.0.1:9877] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9878:blk - 3f24ebc" - 4 127.0.0.1:9878] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9879:blk - c086f7b" - 5 127.0.0.1:9879] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9880:blk - 060e261" - 6 127.0.0.1:9880] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9881:blk - 2585ca9" - 7 127.0.0.1:9881] bcast block 113
error 2025-01-03T16:00:25.505 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9882:blk - 8bd6bc5" - 8 127.0.0.1:9882] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9883:blk - f370be8" - 9 127.0.0.1:9883] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9884:blk - 44b7b0d" - 10 127.0.0.1:9884] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9885:blk - 8711b38" - 11 127.0.0.1:9885] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9886:blk - cb3382b" - 12 127.0.0.1:9886] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9887:blk - 85a259a" - 13 127.0.0.1:9887] bcast block 113
error 2025-01-03T16:00:25.506 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9901:blk - be440e0" - 42 127.0.0.1:58406] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9888:blk - 8520f3b" - 14 127.0.0.1:9888] bcast block 113
error 2025-01-03T16:00:25.506 net-1     net_plugin.cpp:2749           operator()           ] ["localhost:9890:blk - ed19614" - 16 127.0.0.1:9890] bcast block 113
error 2025-01-03T16:00:25.506 net-1     net_plugin.cpp:2749           operator()           ] ["localhost:9892:blk - 2c9c457" - 18 127.0.0.1:9892] bcast block 113
error 2025-01-03T16:00:25.506 net-1     net_plugin.cpp:2749           operator()           ] ["localhost:9893:blk - d48054a" - 19 127.0.0.1:9893] bcast block 113
error 2025-01-03T16:00:25.506 net-3     net_plugin.cpp:2749           operator()           ] ["localhost:9889:blk - e1c6399" - 15 127.0.0.1:9889] bcast block 113
error 2025-01-03T16:00:25.506 net-2     net_plugin.cpp:2749           operator()           ] ["localhost:9891:blk - 7ac6fa8" - 17 127.0.0.1:9891] bcast block 113
error 2025-01-03T16:00:25.506 net-1     net_plugin.cpp:2749           operator()           ] ["localhost:9894:blk - 6f35397" - 20 127.0.0.1:9894] bcast block 113
error 2025-01-03T16:00:25.506 net-0     net_plugin.cpp:2749           operator()           ] ["localhost:9876 - c84cc39" - 31 127.0.0.1:58604] bcast block 113
```

### PR DESCRIPTION
**Pull request by heifner**
The duplication logic for P2P connections was overly complicated. The `node_id` should be more than sufficient to distinguish between two connections.

Resolves #1092

### CODE REVIEW

File: plugins/net_plugin/net_plugin.cpp [hunk 1]
```diff
@@ -3338,31 +3337,6 @@ namespace eosio {
                fc_dlog( logger, "dup check: connected ${c}, ${l} =? ${r}",
                         ("c", check->connected())("l", check->last_handshake_recv.node_id)("r", msg.node_id) );
                if(check->connected() && check->last_handshake_recv.node_id == msg.node_id) {
```
Comment (greg7mdp) [inline plugins/net_plugin/net_plugin.cpp:3339]: Let's just `return check->connected() && check->last_handshake_recv.node_id == msg.node_id;`

**Review by greg7mdp — CHANGES_REQUESTED** [review]

File: plugins/net_plugin/net_plugin.cpp (hunk 1 above)
Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp]: Done

**Review by greg7mdp — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
category: Enhancements
component: P2P
summary: Simplify and improve duplicate connection logic.
Note:end

**Review by spoonincode — APPROVED** [review]
