### PR TITLE
Clamp previously elapsed time to max trx time

### LINKED ISSUE #1797: Test failure: max transaction time
Test failure: https://github.com/AntelopeIO/spring/actions/runs/16605352660/job/46976527026
Cluster `setcode` of `eosio` system contract was forked out. So the `init` failed. 
We didn't look very deep to find out why there was a fork. Might be interesting to look a bit deeper at that.

We did notice this repeated failure trying to place the `setcode` into a block.
```
debug 2025-07-29T19:35:58.971 nodeos    producer_plugin.cpp:2640      handle_push_result   ] [TRX_TRACE] Speculative execution COULD NOT FIT, elapsed 570604us, tx: 25cc8cb32aad061bf0a54a17d4583cd3aaa876d0e6b468afcf8d636499c61dd9 RETRYING
debug 2025-07-29T19:35:59.439 nodeos    producer_plugin.cpp:2640      handle_push_result   ] [TRX_TRACE] Speculative execution COULD NOT FIT, elapsed 264458us, tx: 25cc8cb32aad061bf0a54a17d4583cd3aaa876d0e6b468afcf8d636499c61dd9 RETRYING
info  2025-07-29T19:35:59.514 nodeos    controller.cpp:3895           apply_block          ] Interrupt of trx id: 25cc8cb32aad061bf0a54a17d4583cd3aaa876d0e6b468afcf8d636499c61dd9
debug 2025-07-29T19:35:59.515 nodeos    producer_plugin.cpp:2595      push_transaction     ] [TRX_TRACE] Block 134 for producer defproducera COULD NOT FIT, prev elapsed 570604us, block cpu limit 399900, tx: 25cc8cb32aad061bf0a54a17d4583cd3aaa876d0e6b468afcf8d636499c61dd9 RETRYING 
debug 2025-07-29T19:35:59.515 nodeos    producer_plugin.cpp:2595      push_transaction     ] [TRX_TRACE] Block 134 for producer defproducera COULD NOT FIT, prev elapsed 570604us, block cpu limit 399900, tx: 25cc8cb32aad061bf0a54a17d4583cd3aaa876d0e6b468afcf8d636499c61dd9 RETRYING 
debug 2025-07-29T19:35:59.963 nodeos    producer_plugin.cpp:2595      push_transaction     ] [TRX_TRACE] Block 135 for producer defproducera COULD NOT FIT, prev elapsed 570604us, block cpu limit 399900, tx: 25cc8cb32aad061bf0a54a17d4583cd3aaa876d0e6b468afcf8d636499c61dd9 RETRYING 
```
It would not retry the transaction because 570604us > 399900us. See https://github.com/AntelopeIO/spring/pull/1740

This is because #1740 assumed it was not possible for a transaction to run longer than block time. This did run longer than block time because `max-transaction-time` was set to `-1` on the node. Seems we should either remove the ability to set unlimited speculative trx execution or we should modify the logic of #1470 to allow a retry if prev elapsed is greater than block time.

### PR DESCRIPTION
**Pull request by heifner**
See #1740.

This pull request improves the logic for skipping a transaction retry. We now only skip if the remaining block time is less than the transaction's previous execution time, with the added condition that the previous execution time cannot exceed the on-chain `max_transaction_cpu_usage`.

Resolves #1797

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]

File: plugins/producer_plugin/producer_plugin.cpp [hunk 1]
```diff
@@ -2577,15 +2577,23 @@ producer_plugin_impl::push_result producer_plugin_impl::push_transaction(const f
    if (!disable_subjective_enforcement)
       sub_bill = subjective_bill.get_subjective_bill(first_auth, fc::time_point::now());
 
-   const auto prev_elapsed_time_us = trx->elapsed_time_us;
+   auto prev_elapsed_time_us = trx->elapsed_time_us;
    const auto prev_billed_cpu_time_us = trx->billed_cpu_time_us;
    if (in_producing_mode() && prev_elapsed_time_us > 0) {
+      const fc::microseconds block_time_remaining_us = block_deadline - start;
```
Comment (greg7mdp) [inline plugins/producer_plugin/producer_plugin.cpp:2583]: nit: I'd move this line closer to where it is used (before #2594)

**Review by greg7mdp — APPROVED** [review]

File: plugins/producer_plugin/producer_plugin.cpp (hunk 1 above)
Comment (heifner) [reply plugins/producer_plugin/producer_plugin.cpp]: https://github.com/AntelopeIO/spring/pull/1803/commits/c817915663647803e9d1b7c24032b4b5021ddf6f

**Review by greg7mdp — APPROVED** [review]
