### PR TITLE
Test: Modify light_validation_skip_cfa to work for both savanna and legacy

### LINKED ISSUE #156: api_tests/light_validation_skip_cfa does not work in Savanna mode
When I made  `light_validation_skip_cfa` run in Legacy and Savanna modes as
```
BOOST_AUTO_TEST_CASE_TEMPLATE( light_validation_skip_cfa, T, testers ) try {
    T chain(setup_policy::full);

```
I got

```
warn  2024-05-16T19:42:01.350 unit_test api_tests.cpp:924             test_method          ] 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block 0000000d97d90b43e800f6cf47555109db4ef1945bcb9c3a4d980b6eb0b17768 previous 0000000c51e97e99bd8a698c89808bc4d4a13951aba234124adc82a8778c3b7d not in fork db
    {"id":"0000000d97d90b43e800f6cf47555109db4ef1945bcb9c3a4d980b6eb0b17768","p":"0000000c51e97e99bd8a698c89808bc4d4a13951aba234124adc82a8778c3b7d"}
    unit_test  controller.cpp:3904 operator()

3030001 unlinkable_block_exception: Unlinkable block
unlinkable block 0000000d97d90b43e800f6cf47555109db4ef1945bcb9c3a4d980b6eb0b17768 previous 0000000c51e97e99bd8a698c89808bc4d4a13951aba234124adc82a8778c3b7d not in fork db
    {"id":"0000000d97d90b43e800f6cf47555109db4ef1945bcb9c3a4d980b6eb0b17768","p":"0000000c51e97e99bd8a698c89808bc4d4a13951aba234124adc82a8778c3b7d"}
    unit_test  controller.cpp:3904 operator()
rethrow
    {}
    unit_test  api_tests.cpp:924 test_method

unknown location(0): fatal error: in "api_tests/light_validation_skip_cfa<eosio__testing__savanna_tester>": std::runtime_error: Caught Unexpected Exception
lh@lh-NUC13ANKi5:~$
```

This is the only test in `api_tests` not working in Savanna.

### PR DESCRIPTION
**Pull request by heifner**
Resolves #156

### CODE REVIEW

File: unittests/api_tests.cpp [hunk 1]
```diff
@@ -920,7 +920,8 @@ BOOST_AUTO_TEST_CASE( light_validation_skip_cfa ) try {
    auto check_action_traces = [](const auto& t, const auto& ot) {
       BOOST_CHECK_EQUAL("", ot.console); // cfa not executed for light validation (trusted producer)
       BOOST_CHECK_EQUAL(t.receipt->global_sequence, ot.receipt->global_sequence);
-      BOOST_CHECK_EQUAL(t.digest_legacy(), ot.digest_legacy()); // digest_legacy because test doesn't switch to Savanna
+      BOOST_CHECK_EQUAL(t.digest_legacy(), ot.digest_legacy());
```
Comment (linh2931) [inline unittests/api_tests.cpp:923]: We always check both?

**Review by linh2931 — APPROVED** [review]

**Review by spoonincode — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: STABILITY
category: INTERNALS
summary: Add testing option.
Note:end
