### PR TITLE
[1.1.5] Fix OC scheduling of compiles

### LINKED ISSUE #1441: OC compile scheduling
Fix issue with scheduling of OC compile.

### PR DESCRIPTION
**Pull request by heifner**
Use an unbounded queue for `_result_queue` to avoid results getting dropped because the queue is full. 
Also call `free_code` when code is no longer used instead of waiting for LIB to reduce memory growth.

Resolves #1441

### CODE REVIEW

File: libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp [hunk 1]
```diff
@@ -205,19 +203,20 @@ code_cache_async::get_descriptor_for_code(mode m, const digest_type& code_id, co
...
    g.lock();
-   if(_outstanding_compiles_and_poison.size() >= _threads) {
+   if(_outstanding_compiles >= _threads) {
+      std::vector<char> code{codeobject->code.begin(), codeobject->code.end()};
       if (m.high_priority)
-         _queued_compiles.emplace_front(std::move(msg), std::move(fds_to_pass));
+         _queued_compiles.emplace_front(std::move(msg), std::move(code));
       else
-         _queued_compiles.emplace_back(std::move(msg), std::move(fds_to_pass));
+         _queued_compiles.emplace_back(std::move(msg), std::move(code));
```
Comment (greg7mdp) [inline libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp:213]: Shall we fix the typo in the type `queued_compilies_t`?

**Review by greg7mdp — APPROVED** [review]

File: libraries/chain/include/eosio/chain/wasm_interface_private.hpp [hunk 2]
```diff
@@ -227,10 +232,6 @@ struct eosvmoc_tier {
          // Anything last used before or on the LIB can be evicted.
          const auto first_it = wasm_instantiation_cache.get<by_last_block_num>().begin();
          const auto last_it  = wasm_instantiation_cache.get<by_last_block_num>().upper_bound(lib);
-#ifdef EOSIO_EOS_VM_OC_RUNTIME_ENABLED
-         if(eosvmoc) for(auto it = first_it; it != last_it; it++)
-            eosvmoc->cc.free_code(it->code_hash, it->vm_version);
-#endif
```
Comment (spoonincode) [inline libraries/chain/include/eosio/chain/wasm_interface_private.hpp:233]: The changes aren't what we discussed. afaict the way we discussed would be 1) for this code to remain here, and 2) for the added lines above (where this here was moved to) would exist but would check that the code was set in the same block prior to doing the removal. That `first_block_used` is currently inaccessible from there but it would be trivial to plumb it through starting from here
https://github.com/AntelopeIO/spring/blob/504fa82dca9172a36056a67dc1932e063bdb6adf/libraries/chain/eosio_contract.cpp#L156-L163

Also, I realize now the discussion might have been ambiguous w.r.t. to us making this change strictly for OC or more universally. I believe the problem we are trying to solve applies for any runtime not just OC so I suspect we should be doing this universally. Maybe this aspect needs to be discussed idk

Comment (heifner) [reply libraries/chain/include/eosio/chain/wasm_interface_private.hpp]: https://github.com/AntelopeIO/spring/pull/1447/commits/2a890fcfa4701cd4dd4b2658a4ee8c7b4e755bcd https://github.com/AntelopeIO/spring/pull/1447/commits/f6ad1370d6af23e3337bc4232dba40668417d379

**Review by spoonincode — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]
