### PR TITLE
Remove invalid assertion for action_mroot

### LINKED ISSUE #168: `assert(!action_mroot.empty())` in `valid_t block_state::new_valid()` should not be needed
When running `eosio_system_part1_tests/stake_unstake` under Savanna,

I got
`unit_test: .../libraries/chain/block_state.cpp:283: eosio::chain::valid_t eosio::chain::block_state::new_valid(const eosio::chain::block_header_state&, const digest_type&, const digest_type&) const: Assertion `!action_mroot.empty()' failed``

https://github.com/AntelopeIO/spring/blob/a7816091b06fac4702e0c131cfe269f08df9cdd7/libraries/chain/block_state.cpp#L283
should not be needed, as it is possible a block is empty.

### PR DESCRIPTION
**Pull request by heifner**
- `action_mroot` can be empty if `onblock` fails
- Add test for a failing `onblock`

Resolves #168

### CODE REVIEW

**Review by spoonincode — APPROVED** [review]

File: unittests/block_tests.cpp [hunk 1]
```diff
@@ -344,4 +345,42 @@ BOOST_FIXTURE_TEST_CASE( abort_block_transactions_tester, validating_tester) { t
 
    } FC_LOG_AND_RETHROW() }
 
+BOOST_AUTO_TEST_CASE_TEMPLATE(no_onblock_test, T, testers) { try {
```
Comment (linh2931) [inline unittests/block_tests.cpp:348]: Maybe add a summary about the purpose of this test.

**Review by linh2931 — APPROVED** [review]

File: unittests/block_tests.cpp (hunk 1 above)
Comment (linh2931) [reply unittests/block_tests.cpp:349]: Thanks.

**Comment by ericpassmore** [comment]
Note:start
group: STABILITY
category: TEST
summary: Remove unneeded check, as it was causing test failures for legitimate empty block scenarios.
Note:end
