### PR TITLE
Fix interrupt transaction race condition

### LINKED ISSUE #1095: test failure: restart-scenarios-if-test-resync
https://github.com/AntelopeIO/spring/actions/runs/12656370912/job/35269365364

### PR DESCRIPTION
**Pull request by heifner**
The support for interrupting transaction on new best head, #1047, has a race condition such that an interrupt could interrupt a speculative transaction instead of a transaction in apply block. This would cause the transaction to fail and not be re-tried on the node. 

This PR refactors the `platform_timer` to keep track if it was trigger by an explicit interrupt or by the timer timing out. This allows for `transaction_context::checktime` to directly tell if a transaction was interrupted and raise an appropriate interrupt exception. If a transaction is interrupted it can then be retried similar to how a transaction is retried if it hits a block boundary.

Resolves #1095

### CODE REVIEW

File: libraries/chain/include/eosio/chain/platform_timer.hpp [hunk 1]
```diff
@@ -17,7 +15,8 @@ struct platform_timer {
 
    void start(fc::time_point tp);
    void stop();
-   void expire_now();
+   void interrupt_timer();
+   void _expire_now(); // called by internal timer
```
[the remark this answers is not in the document]
Comment (heifner) [reply libraries/chain/include/eosio/chain/platform_timer.hpp:19]: Not without some friends and with the multiple impls that becomes rather a pain.

[the remark this answers is not in the document]
Comment (heifner) [reply libraries/chain/include/eosio/chain/platform_timer.hpp:19]: Hmm, I'm a bit surprised that worked.

File: libraries/chain/platform_timer_accuracy.cpp [hunk 2]
```diff
@@ -39,9 +39,10 @@ void compute_and_print_timer_accuracy(platform_timer& timer) {
       for(unsigned int i = 0; i < loops; ++i) {
          auto start = std::chrono::high_resolution_clock::now();
          timer.start(fc::time_point(fc::time_point::now().time_since_epoch() + fc::microseconds(interval)));
-         while(!timer.expired) {}
+         while(timer.timer_state() == platform_timer::state_t::running) {}
          auto end = std::chrono::high_resolution_clock::now();
          int timer_slop = std::chrono::duration_cast<std::chrono::microseconds>(end-start).count() - interval;
+         timer.stop();
```
Comment (greg7mdp) [inline libraries/chain/platform_timer_accuracy.cpp:45]: Not seeing why this added line is necessary?

File: libraries/chain/platform_timer_asio_fallback.cpp [hunk 3]
```diff
@@ -75,18 +75,25 @@ void platform_timer::start(fc::time_point tp) {
...
       call_expiration_callback();
    }
 }
 
 void platform_timer::stop() {
-   if(expired)
+   if(_state == state_t::stopped)
       return;
 
    my->timer->cancel();
```
Comment (greg7mdp) [inline libraries/chain/platform_timer_asio_fallback.cpp:95]: Wouldn't it make sense to call `my->timer->cancel();` only if `(_state == state_t::running)`?

File: libraries/chain/platform_timer_asio_fallback.cpp [hunk 4]
```diff
@@ -75,18 +75,25 @@ void platform_timer::start(fc::time_point tp) {
...
-   if (expired.compare_exchange_strong(expected, true)) {
+   state_t expected = state_t::running;
+   if (_state.compare_exchange_strong(expected, state_t::timed_out)) {
+      call_expiration_callback();
+   }
+}
+
+void platform_timer::interrupt_timer() {
+   state_t expected = state_t::running;
+   if (_state.compare_exchange_strong(expected, state_t::interrupted)) {
```
Comment (greg7mdp) [inline libraries/chain/platform_timer_asio_fallback.cpp:86]: Why don't these call `my->timer->cancel()`?

Isn't it possible that someone calls `interrupt_timer() ` (which updates the state but doesn't cancel the `async_wait`), and then calls `start(fc::time_point::maximum())`, and may be surprised when the previous `async_wait` expires the timer.

File: libraries/chain/platform_timer_accuracy.cpp (hunk 2 above)
Comment (heifner) [reply libraries/chain/platform_timer_accuracy.cpp:45]: I added it because I originally added an assert that start() only called when timer is stopped. However, we don't actually honor that constraint currently elsewhere. Seems like it is better to honor that constraint normally.

**Comment by ericpassmore** [comment]
Note:start
category: System Stability
component: Internal
summary: Fix a race condition where an interrupt could interrupt a speculative transaction.
Note:end

File: libraries/chain/platform_timer_asio_fallback.cpp (hunk 4 above)
Comment (heifner) [reply libraries/chain/platform_timer_asio_fallback.cpp:86]: We would need to add a mutex around the timer to do that. I think the intention is that stop() should be called before calling start() again.

File: libraries/chain/platform_timer_accuracy.cpp (hunk 2 above)
Comment (heifner) [reply libraries/chain/platform_timer_accuracy.cpp:45]: Decided it best to fix the invariant that `stop()` always called before `stop()`. Surprise-surprise the issue there is with deferred-transactions.

File: libraries/chain/platform_timer_asio_fallback.cpp (hunk 3 above)
Comment (heifner) [reply libraries/chain/platform_timer_asio_fallback.cpp:95]: This now needs to set to stopped, so the assert on start() is not triggered.

**Review by greg7mdp — APPROVED** [review]

**Comment by spoonincode** [comment]
interestingly, ARM prior to 8.3 generates calls to library code for these CAS. It's probably benign library code that doesn't change much and can be audited. Still, it may be a compelling reason to require 8.3+ if we ever have proper ARM support.

**Review by spoonincode — APPROVED** [review]
It would be nice to acquire/release the atomic, but that can be done later
