### PR TITLE
Store proposed producers and proposed finalizers in building block

### LINKED ISSUE #182: Nodeos Crashes after actfinkey action
There are 3 nodeos processes each with a different registered block producer. Setup in a private network running Savanna consensus. Steps to reproduce 
- create a new 4th BLS key via spring-utils
- add key to config as `signature-provided`
- restart nodeos for one producer 
- register new key with producer name
- activate newly registered  key 

[bt_all_threads.txt](https://github.com/AntelopeIO/spring/files/15393788/bt_all_threads.txt)

```
nodeos --full-version
info  2024-05-21T18:08:14.494 nodeos    main.cpp:151                  main                 ] nodeos started
v1.0.0-dev-2187c808682a05270025a4de751e6c16667a0274
```

reference-contracts commit `cd645b54a176f0c8b5f2f5ea9b21f47b7f9bf7eb` using `system-contract`

Commands Used
```
# register key 
cleos --url $ENDPOINT push action eosio regfinkey "{\"finalizer_name\":\"${producer_name:?}\", \
                            \"finalizer_key\":\"${PUBLIC_KEY:?}\", \
                            \"proof_of_possession\":\"${PROOF_POSSESION:?}\"}" -p ${producer_name:?}

# send actkey action
cleos --url $ENDPOINT push action eosio actfinkey "{\"finalizer_name\":\"${producer_name:?}\", \
                            \"finalizer_key\":\"${PUBLIC_KEY:?}\"}" -p ${producer_name:?}
```

Table output before called `actfinkey`
```
enfuser@6045285f2fdd:/local/eosnetworkfoundation/repos/bootstrap-private-network/bin$ cleos --url $ENDPOINT get table eosio eosio finalizers
{
  "rows": [{
      "finalizer_name": "bpa",
      "active_key_id": 0,
      "active_key_binary": "1f3758885c8eb448340fee9e2e256e6d58f53a7f701f404b3f4619e9d04fc15504c39477bebf711cf219fb0376ea2716fa4641278192af68a6675a2ab853326d85d985dfa3098e813e70b08b3ff5eb665ece1acf42d92b89b7a86807e6eb4512",
      "finalizer_key_count": 1
    },{
      "finalizer_name": "bpb",
      "active_key_id": 1,
      "active_key_binary": "b3064e0e296d2d7c3dd65517ae11a6333abd54deb2ab630bac61b82f2f9039b7e781d19105d9e4d23d3842e068e42e14a5c10857114f22f66641f187d5231f2f1553ebb7381d163a558a4636898dc6541c304e3892b3576f53579146d3af9302",
      "finalizer_key_count": 2
    },{
      "finalizer_name": "bpc",
      "active_key_id": 2,
      "active_key_binary": "83b3c92a076c2c9edc28838a5b840d65e58ea38fd05b55313e85751348433280d996fd55b75d43374022bca025d0c4190311705aa37d8f020d614a1fed7153b0e89a1cbb9e47e8637f1154ed2c478725e10c2d50426b3a02db80bb30ae522a13",
      "finalizer_key_count": 1
    }
  ],
  "more": false,
  "next_key": ""
}
enfuser@6045285f2fdd:/local/eosnetworkfoundation/repos/bootstrap-private-network/bin$ cleos --url $ENDPOINT get table eosio eosio finkeys
{
  "rows": [{
      "id": 0,
      "finalizer_name": "bpa",
      "finalizer_key": "PUB_BLS_HzdYiFyOtEg0D-6eLiVubVj1On9wH0BLP0YZ6dBPwVUEw5R3vr9xHPIZ-wN26icW-kZBJ4GSr2imZ1oquFMybYXZhd-jCY6BPnCwiz_162ZezhrPQtkribeoaAfm60USeSFQMg",
      "finalizer_key_binary": "1f3758885c8eb448340fee9e2e256e6d58f53a7f701f404b3f4619e9d04fc15504c39477bebf711cf219fb0376ea2716fa4641278192af68a6675a2ab853326d85d985dfa3098e813e70b08b3ff5eb665ece1acf42d92b89b7a86807e6eb4512"
    },{
      "id": 1,
      "finalizer_name": "bpb",
      "finalizer_key": "PUB_BLS_swZODiltLXw91lUXrhGmMzq9VN6yq2MLrGG4Ly-QObfngdGRBdnk0j04QuBo5C4UpcEIVxFPIvZmQfGH1SMfLxVT67c4HRY6VYpGNomNxlQcME44krNXb1NXkUbTr5MC65Ktqg",
      "finalizer_key_binary": "b3064e0e296d2d7c3dd65517ae11a6333abd54deb2ab630bac61b82f2f9039b7e781d19105d9e4d23d3842e068e42e14a5c10857114f22f66641f187d5231f2f1553ebb7381d163a558a4636898dc6541c304e3892b3576f53579146d3af9302"
    },{
      "id": 2,
      "finalizer_name": "bpc",
      "finalizer_key": "PUB_BLS_g7PJKgdsLJ7cKIOKW4QNZeWOo4_QW1UxPoV1E0hDMoDZlv1Vt11DN0AivKAl0MQZAxFwWqN9jwINYUof7XFTsOiaHLueR-hjfxFU7SxHhyXhDC1QQms6AtuAuzCuUioTb4wE_w",
      "finalizer_key_binary": "83b3c92a076c2c9edc28838a5b840d65e58ea38fd05b55313e85751348433280d996fd55b75d43374022bca025d0c4190311705aa37d8f020d614a1fed7153b0e89a1cbb9e47e8637f1154ed2c478725e10c2d50426b3a02db80bb30ae522a13"
    },{
      "id": 3,
      "finalizer_name": "bpb",
      "finalizer_key": "PUB_BLS_jU4vH-DERn5BJEkNU6y1iGLjcJhcyp1I77TENbfbqP18K7sRaCSl272nHebpJG4MkfteRzZ2TLpnhrN7RpX-rTukejyHIBNT6lqjzE_nNa1hwjZKw49t5GQXaA4nkzkJ-lhVeA",
      "finalizer_key_binary": "8d4e2f1fe0c4467e4124490d53acb58862e370985cca9d48efb4c435b7dba8fd7c2bbb116824a5dbbda71de6e9246e0c91fb5e4736764cba6786b37b4695fead3ba47a3c87201353ea5aa3cc4fe735ad61c2364ac38f6de46417680e27933909"
    }
  ],
  "more": false,
  "next_key": ""
}
```

### PR DESCRIPTION
**Pull request by heifner**
The chainbase `global_property_object` was used to store `finalizer_policy` during block construction as a means to provide automatic rollback if the transaction/block failed. See https://github.com/AntelopeIO/spring/pull/99. However, `finalizer_policy` contains non-shared types of `std::vector` and `fc::crypto::blslib::bls_public_key`. 

This PR solves the problem of avoiding side-effects of proposed finalizer policy made in an aborted transaction in a different way than committing the speculative changes into the `global_property_object` in `chainbase`. Now we store the speculative changes in the transaction context. Then if we commit the transaction, it copies them over (assuming they are not nullopt) from the transaction context to the building block. This avoids having to add a shared version of the `finalizer_policy` and `bls_public_key`. 

For symmetry, the proposer schedule in Savanna was modified to also be managed the same way as `finalier_policy` in `transaction_context`.

This PR removes  `proposed_fin_pol_block_num` and `proposed_fin_pol` from `global_property_object` and therefore is not state compatible with previous versions. The proposed schedule `proposed_schedule_block_num` & `proposed_schedule` were not removed from `global_property_object` because they are still needed pre-Savanna.

Resolves #182

### CODE REVIEW

**Comment by ericpassmore** [comment]
Validated this works, no crash. Log message `New finalizer policy becoming active in block` seems to be duplicated. Checked that the correct key was in use by the block producer. 

```
info  2024-05-22T18:52:29.054 net-1     block_header_state.cpp:262    finish_next          ] Finalizer policy generation change: 1 -> 2
info  2024-05-22T18:52:29.054 net-1     block_header_state.cpp:264    finish_next          ] New finalizer policy becoming active in block 000005a11f0af1785746b07b1a8bee85ec54fe1961464897976b1134cad11337: {"generation":2,"threshold":3,"finalizers":[{"description":"bpa","weight":1,"public_key":"PUB_BLS_GMw0JRDY2nUeSszpW_OHb8xjfCc61FP_Ei9qoZ63r_-twOPn9fTOeHDDFccYgL8Ar7NbwrV-Z9RJXrTSNPtEjEbdJwnSsgsaIulRIDwFGiKg0XQuABfEhhyGxklXORQTEvep8Q"},{"description":"bpc","weight":1,"public_key":"PUB_BLS_kIQ5EsjgIyL8XUDWqeTn6BrZCi0ziS7Wx8tAFEADMIvFPS_j8mmqe-8fvdet8E4KwPfRMOyOcf3qY7wN-TCN6piHLLxn1CMlzRGpWwdT8b1cki9GG0gRT1ExOrgY8hcLmVB8Nw"},{"description":"bpb","weight":1,"public_key":"PUB_BLS_woMzcifQYxMIuh227prW04BoGScfV_67RUDcsnu4CqeOOHNq5TKkHIlpVG9j13IX_tWjAWPZ-oft1Hxj5yG5YQi2mPDxtSTDmOPU00TfHRsaBIfZFcgx3-Pqy2D3I1UO5NeStA"}]}
info  2024-05-22T18:52:29.059 nodeos    block_header_state.cpp:262    finish_next          ] Finalizer policy generation change: 1 -> 2
info  2024-05-22T18:52:29.059 nodeos    block_header_state.cpp:264    finish_next          ] New finalizer policy becoming active in block 000005a11f0af1785746b07b1a8bee85ec54fe1961464897976b1134cad11337: {"generation":2,"threshold":3,"finalizers":[{"description":"bpa","weight":1,"public_key":"PUB_BLS_GMw0JRDY2nUeSszpW_OHb8xjfCc61FP_Ei9qoZ63r_-twOPn9fTOeHDDFccYgL8Ar7NbwrV-Z9RJXrTSNPtEjEbdJwnSsgsaIulRIDwFGiKg0XQuABfEhhyGxklXORQTEvep8Q"},{"description":"bpc","weight":1,"public_key":"PUB_BLS_kIQ5EsjgIyL8XUDWqeTn6BrZCi0ziS7Wx8tAFEADMIvFPS_j8mmqe-8fvdet8E4KwPfRMOyOcf3qY7wN-TCN6piHLLxn1CMlzRGpWwdT8b1cki9GG0gRT1ExOrgY8hcLmVB8Nw"},{"description":"bpb","weight":1,"public_key":"PUB_BLS_woMzcifQYxMIuh227prW04BoGScfV_67RUDcsnu4CqeOOHNq5TKkHIlpVG9j13IX_tWjAWPZ-oft1Hxj5yG5YQi2mPDxtSTDmOPU00TfHRsaBIfZFcgx3-Pqy2D3I1UO5NeStA"}]}
```

```
cleos get table eosio eosio finalizers
{
  "rows": [{
      "finalizer_name": "bpa",
      "active_key_id": 0,
      "active_key_binary": "18cc342510d8da751e4acce95bf3876fcc637c273ad453ff122f6aa19eb7afffadc0e3e7f5f4ce7870c315c71880bf00afb35bc2b57e67d4495eb4d234fb448c46dd2709d2b20b1a22e951203c051a22a0d1742e0017c4861c86c64957391413",
      "finalizer_key_count": 1
    },{
      "finalizer_name": "bpb",
      "active_key_id": 3,
      "active_key_binary": "c283337227d0631308ba1db6ee9ad6d3806819271f57febb4540dcb27bb80aa78e38736ae532a41c8969546f63d77217fed5a30163d9fa87edd47c63e721b96108b698f0f1b524c398e3d4d344df1d1b1a0487d915c831dfe3eacb60f723550e",
      "finalizer_key_count": 2
    },{
      "finalizer_name": "bpc",
      "active_key_id": 2,
      "active_key_binary": "90843912c8e02322fc5d40d6a9e4e7e81ad90a2d33892ed6c7cb40144003308bc53d2fe3f269aa7bef1fbdd7adf04e0ac0f7d130ec8e71fdea63bc0df9308dea98872cbc67d42325cd11a95b0753f1bd5c922f461b48114f51313ab818f2170b",
      "finalizer_key_count": 1
    }
  ],
  "more": false,
  "next_key": ""
}
```
```
 cleos get table eosio eosio finkeys   
{
  "rows": [{
      "id": 0,
      "finalizer_name": "bpa",
      "finalizer_key": "PUB_BLS_GMw0JRDY2nUeSszpW_OHb8xjfCc61FP_Ei9qoZ63r_-twOPn9fTOeHDDFccYgL8Ar7NbwrV-Z9RJXrTSNPtEjEbdJwnSsgsaIulRIDwFGiKg0XQuABfEhhyGxklXORQTEvep8Q",
      "finalizer_key_binary": "18cc342510d8da751e4acce95bf3876fcc637c273ad453ff122f6aa19eb7afffadc0e3e7f5f4ce7870c315c71880bf00afb35bc2b57e67d4495eb4d234fb448c46dd2709d2b20b1a22e951203c051a22a0d1742e0017c4861c86c64957391413"
    },{
      "id": 1,
      "finalizer_name": "bpb",
      "finalizer_key": "PUB_BLS_OKiUyiTv4_KbgO2AaGO4xRUIgdwY4kl0itPqfjpVtgPh_Pyq9fA7sUsHzVd3QToE6dsjEDnTUaM9CkF08IGUus2FTq7No5biTa3IR3vgYFFyj3GK4ejzhfyUc-nERNoLUn0OOA",
      "finalizer_key_binary": "38a894ca24efe3f29b80ed806863b8c5150881dc18e249748ad3ea7e3a55b603e1fcfcaaf5f03bb14b07cd5777413a04e9db231039d351a33d0a4174f08194bacd854eaecda396e24dadc8477be06051728f718ae1e8f385fc9473e9c444da0b"
    },{
      "id": 2,
      "finalizer_name": "bpc",
      "finalizer_key": "PUB_BLS_kIQ5EsjgIyL8XUDWqeTn6BrZCi0ziS7Wx8tAFEADMIvFPS_j8mmqe-8fvdet8E4KwPfRMOyOcf3qY7wN-TCN6piHLLxn1CMlzRGpWwdT8b1cki9GG0gRT1ExOrgY8hcLmVB8Nw",
      "finalizer_key_binary": "90843912c8e02322fc5d40d6a9e4e7e81ad90a2d33892ed6c7cb40144003308bc53d2fe3f269aa7bef1fbdd7adf04e0ac0f7d130ec8e71fdea63bc0df9308dea98872cbc67d42325cd11a95b0753f1bd5c922f461b48114f51313ab818f2170b"
    },{
      "id": 3,
      "finalizer_name": "bpb",
      "finalizer_key": "PUB_BLS_woMzcifQYxMIuh227prW04BoGScfV_67RUDcsnu4CqeOOHNq5TKkHIlpVG9j13IX_tWjAWPZ-oft1Hxj5yG5YQi2mPDxtSTDmOPU00TfHRsaBIfZFcgx3-Pqy2D3I1UO5NeStA",
      "finalizer_key_binary": "c283337227d0631308ba1db6ee9ad6d3806819271f57febb4540dcb27bb80aa78e38736ae532a41c8969546f63d77217fed5a30163d9fa87edd47c63e721b96108b698f0f1b524c398e3d4d344df1d1b1a0487d915c831dfe3eacb60f723550e"
    }
  ],
  "more": false,
  "next_key": ""
}
```

**Comment by ericpassmore** [comment]
Reran the tests. 

- Transition to Savanna at block `187` 
- Stopped rodeos instance 2 after LIB  `434` `2024-05-22T20:08:28.000`
- Restarted and ran network to LIB `493` `2024-05-22T20:08:56.000`
- Registered New BLS Key 
- Ran network to LIB `611` `2024-05-22T20:09:56.500`
- `Actfinkey` policy change in log between `641` and `642`
- Checked network LIB `644` `2024-05-22T20:10:13.000`

```
info  2024-05-22T20:06:23.964 nodeos    controller.cpp:1363           transition_to_savann ] Transitioning to savanna, IF Genesis Block 140, IF Critical Block 186
info  2024-05-22T20:06:23.964 nodeos    controller.cpp:1384           operator()           ] Transition to instant finality happening after block 186, First IF Proper Block 187
```

```
2024-05-22T20:10:13.000 signed by bpa [trxs: 0, lib: 641, net: 0, cpu: 100, elapsed: 105, time: 321, latency: -102 ms]
info  2024-05-22T20:10:13.353 net-1     block_header_state.cpp:262    finish_next          ] Finalizer policy generation change: 1 -> 2
info  2024-05-22T20:10:13.354 net-1     block_header_state.cpp:264    finish_next          ] New finalizer policy becoming active in block 000002857cafecb928e1194e9be0817de6c53665829c2b1fa1765f1f69072000: {"generation":2,"threshold":3,"finalizers":[{"description":"bpa","weight":1,"public_key":"PUB_BLS__R2F6U9SbAxXUq79ro6BFhFqhY2KTDZ2wvpbSt0WxQn1Ps4Lh-h923lSOPdsEoMBGfG1TMTJsakaiSztWsjygRT-V7OO9SYa9kpe0WA40e9anSaCkcGnDu4WIWwRxA8W60VBRw"},{"description":"bpc","weight":1,"public_key":"PUB_BLS_RBLVFJB_CdRWGl_PTvLQjLT2z-riKPGjPzeJb4McgmEJKM1vUusfVd35YQz5_DEDg0Wnj5z4JTbbt4X9Zo-hw4oeUeLboK16NBQ8GxgkI4YPXNDo3E3Fvv8UfCjFyjIPAoGbpA"},{"description":"bpb","weight":1,"public_key":"PUB_BLS_woMzcifQYxMIuh227prW04BoGScfV_67RUDcsnu4CqeOOHNq5TKkHIlpVG9j13IX_tWjAWPZ-oft1Hxj5yG5YQi2mPDxtSTDmOPU00TfHRsaBIfZFcgx3-Pqy2D3I1UO5NeStA"}]}
info  2024-05-22T20:10:13.360 nodeos    block_header_state.cpp:262    finish_next          ] Finalizer policy generation change: 1 -> 2
info  2024-05-22T20:10:13.360 nodeos    block_header_state.cpp:264    finish_next          ] New finalizer policy becoming active in block 000002857cafecb928e1194e9be0817de6c53665829c2b1fa1765f1f69072000: {"generation":2,"threshold":3,"finalizers":[{"description":"bpa","weight":1,"public_key":"PUB_BLS__R2F6U9SbAxXUq79ro6BFhFqhY2KTDZ2wvpbSt0WxQn1Ps4Lh-h923lSOPdsEoMBGfG1TMTJsakaiSztWsjygRT-V7OO9SYa9kpe0WA40e9anSaCkcGnDu4WIWwRxA8W60VBRw"},{"description":"bpc","weight":1,"public_key":"PUB_BLS_RBLVFJB_CdRWGl_PTvLQjLT2z-riKPGjPzeJb4McgmEJKM1vUusfVd35YQz5_DEDg0Wnj5z4JTbbt4X9Zo-hw4oeUeLboK16NBQ8GxgkI4YPXNDo3E3Fvv8UfCjFyjIPAoGbpA"},{"description":"bpb","weight":1,"public_key":"PUB_BLS_woMzcifQYxMIuh227prW04BoGScfV_67RUDcsnu4CqeOOHNq5TKkHIlpVG9j13IX_tWjAWPZ-oft1Hxj5yG5YQi2mPDxtSTDmOPU00TfHRsaBIfZFcgx3-Pqy2D3I1UO5NeStA"}]}
info  2024-05-22T20:10:13.360 nodeos    controller.cpp:3457           log_applied          ] Received block 7cafecb928e1194e... #645 @ 2024-05-22T20:10:13.500 signed by bpa [trxs: 0, lib: 642, net: 0, cpu: 100, elapsed: 86, time: 357, latency: -139 ms]
```

**Review by linh2931 — APPROVED** [review]

File: libraries/chain/webassembly/privileged.cpp [hunk 1]
```diff
@@ -85,7 +85,7 @@ namespace eosio { namespace chain { namespace webassembly {
       }
       EOS_ASSERT( producers.size() == unique_producers.size(), wasm_execution_error, "duplicate producer name in producer schedule" );
 
-      return context.control.set_proposed_producers( std::move(producers) );
+      return context.control.set_proposed_producers( context.trx_context, std::move(producers) );
```
Comment (linh2931) [inline libraries/chain/webassembly/privileged.cpp:88]: Why not call `context.trx_context.set_proposed_producers()` in the same was as `context.trx_context.set_proposed_finalizers()`?

Comment (heifner) [reply libraries/chain/webassembly/privileged.cpp:88]: Because `controller` currently is in charge of knowing `legacy` vs `savanna` modes. So route it through `controller` so `controller` can dispatch to correct `set_proposed_producers` or `set_proposed_producers_legacy`.

**Comment by heifner** [comment]
> Log message `New finalizer policy becoming active in block` seems to be duplicated.

I will address this in a separate PR.

**Review by spoonincode — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: BUG
summary: Improve data safety for transaction rollback and avoid unintended side effects for a proposed finalizer policy change during an aborted transaction.
Note:end
