### PR TITLE
[1.0.1] Add missing data to block_header_state and change verify_qc_claim to use block_header_state data rather than only looking up a block_state in the fork database

### LINKED ISSUE #694: Add missing data to block_header_state and change verify_qc_claim to use block_header_state data rather than only looking up a block_state in the fork database
## Problem 

The final validations of `verify_proper_block_exts` actually verify that the attached QC is valid:

https://github.com/AntelopeIO/spring/blob/a8159feae6f7f0d89dc0f990682a3b09635a3e1f/libraries/chain/controller.cpp#L3973-L3981

But notice that it assumes the claimed block can be found in the fork database. This is not always going to be true depending on how the node started up. If it started up from a snapshot, it is possible that a later block received from the network advances the QC claim relative to the claim made by the block from the snapshot (which is also the root of the fork database on startup) but to a block that is still an ancestor of that block from the snapshot.

For example, consider the following case:

The node processes the following blockchain:

```
<- B1 <- B2 <- B3 <- B4 <- B5 <- B6
```

where:
B2 claims a strong QC on B1.
B3 claims a strong QC on B1.
B4 claims a strong QC on B2. (B4 makes B1 final.)
B5 claims a strong QC on B4. (B5 makes B2 final.)
B6 claims a strong QC on B5. (B6 makes B4 final.)

Let's say the node operator decided to take a snapshot on B3. After their node receives B6, B4 becomes final and the snapshot on B3 becomes available to the node operator as a valid snapshot.

Then the operator shuts down nodeos and decides to restart from the snapshot on B3.

After starting up from the snapshot, their node receives block B4 from the P2P network. Since B4 advances the QC claim relative to its parent (from a strong QC claimed on B1 to a strong QC claimed on B2), it must include a QC attached to justify its claim. It does in fact contain the strong QC on block B2, but how does this node verify the QC? It started with B3 as the root block of its fork database, so block B2 does not exist in the fork database.

The only information needed to validate a QC on a particular block, beyond the data included in the QC itself, is the following state associated with that particular block: its finality digest (which is also the digest to sign for strong votes and it trivially derives the digest to sign for weak votes); its active finalizer policy; and its pending finalizer policy (if present for that block).

Consider a block `B_new` that has a QC in its QC block extension. This block makes a QC claim on an ancestor block `B_claimed`. And that QC claim must be better than the QC claim of `B_new`'s parent block `B_parent`. `B_parent` makes a QC claim on its ancestor block which we can denote `B_parent_claimed`. So we know that `B_parent_claimed` is either `B_claimed` or an ancestor of `B_claimed`; note that it is possible for `B_parent_claimed` to be `B_claimed` in the case where the `B_parent` makes a claim of a weak QC on `B_parent_claimed` (aka `B_claimed`) while `B_new` makes a claim of a strong QC on `B_claimed` (aka `B_parent_claimed`). 

Fortunately, we know that the `finality_core` in the `block_header_state` of `B_parent` has the finality digests for all of the blocks that are ancestors of `B_parent` up to and including `B_parent_claim`. And of course the finality digest of `B_parent` is known if the `block_header_state` of `B_parent` is available. So no matter which block `B_claimed` happens to be, we know that the finality digest of that block is known using only information available in the `block_header_state` of `B_parent` which should of course be available if evaluating block `B_new`.

Unfortunately, the active (and possibly pending) finalizer policies as of block `B_claimed` are also needed to validate the QC for `B_claimed` (the one attached in the QC block extension of `B_new`). And it might be possible that these policies for `B_claimed` are different than the ones for `B_parent`.

For example, consider the following case:

The node processes the following blockchain:

```
<- B1 <- B2 <- B3 <- B4 <- B5 <- B6 <- B7 <- B8 <- B9
```

where:

B1 has active finalizer policy P1 and pending finalizer policy.
B1 proposes finalizer policy P2.

B2 claims a strong QC on B1.
B2 has active finalizer policy P1 and no pending finalizer policy.

B3 claims a strong QC on B2. (B3 makes B1 final.)
B3 has active finalizer policy P1 and has pending finalizer policy P2.

B4 claims a strong QC on B3. (B4 makes B2 final.)
B4 has active finalizer policy P1 and has pending finalizer policy P2.

B5 claims a strong QC on B3.
B5 has active finalizer policy P1 and has pending finalizer policy P2.

B6 claims a strong QC on B4. (B5 makes B3 final.)
B6 has active finalizer policy P1 and no pending finalizer policy.
(At this point, in the current implementation policy P2 is lost from the `block_header_state` of B6, which is the source of the problem.)

B7 claims a strong QC on B5.
B7 has active finalizer policy P2 and no pending finalizer policy.

B8 claims a strong QC on B6. (B8 makes B4 final.)
B8 has active finalizer policy P2 and no pending finalizer policy.

B9 claims a strong QC on B8. (B9 makes B6 final.)
B9 has active finalizer policy P2 and no pending finalizer policy.

The node operator decided to take a snapshot on B6. After their node receives B9, B6 becomes final and the snapshot on B6 becomes available to the node operator as a valid snapshot.

Then the operator shuts down nodeos and decides to restart from the snapshot on B6.

After starting up from the snapshot, their node receives block B7 from the P2P network. Since B7 advances the QC claim relative to its parent (from a strong QC claimed on B4 to a strong QC claimed on B5), it must include a QC attached to justify its claim. It does in fact contain the strong QC on block B5, but how does this node verify the QC? It started with B6 as the root block of its fork database, so block B5 does not exist in the fork database.

Yes, the finality digest for B5 can be retrieved from the `finality_core` in the `block_header_state` for B6. But the `block_header_state` of B6 contains an `active_finalizer_policy` of policy P2 and it contains no `pending_finalizer_policy`. Not only does it not know the generation numbers for the active and pending (if present) finalizer policies of B5, even if it did know the generation numbers, it simply would no longer have policy P1 which it needs to validate the QC for block B5.

## Solution

The solution is to augment the state tracked in `block_header_state`.

First, the `block_ref` in `finality_core` needs to be expanded to also track the generation number of the active finalizer policy and the generation number of the pending finalizer policy (if it is present). If the pending finalizer policy is not present, then a generation number of 0 can be used to represent the lack of presence (valid generation numbers for finalizer policies start from 1).

Second, all finalizer policies tracked in the `finality_core` starting with the latest QC claim block (that is the block has block number `latest_qc_claim().block_num`) must be kept around in the `block_header_state`. However, due to how promotion of finalizer policies work, we know that the only finalizer policy that we would need to track that is not already tracked with the `active_finalizer_policy` or `pending_finalizer_policy` is the active finalizer policy of the latest QC claim block.

So we just need to store one extra member, called `latest_qc_claim_block_active_finalizer_policy`, in the `block_header_state` to track the active finalizer policy of the latest QC claim block. However, if the latest QC claim block's active finalizer policy is the same as the current block's active finalizer policy (as determined by comparing their generation numbers for equality), then we should not store the redundant finalizer policy (it would be null) so that we do not serialize it out to disk.

We should add the following member function to `block_header_state`:
```cpp
struct finalizer_policies_t {
   digest_type          finality_digest;
   finalizer_policy_ptr active_finalizer_policy; // Never null
   finalizer_policy_ptr pending_finalizer_policy; // Only null if the block has no pending finalizer policy
};

// Only defined for core.latest_qc_claim().block_num <= num <= core.current_block_num()
finalizer_policies_t get_finalizer_policies(block_num_type num);`
```

And we should add the following member function to `block_state`:
```cpp
// Defined for core.last_final_block_num().block_num <= num <= core.current_block_num()
uint32_t get_active_finalizer_policy_generation(block_num_type num);
```

When constructing the next `block_header_state` in `finish_next`, we need to make sure the new `latest_qc_claim_block_active_finalizer_policy` member is properly set. This can be done with the following code:

```cpp
const auto latest_qc_claim_block_num = next_header_state.core.latest_qc_claim().block_num;
const auto active_generation_num = next_header_state.active_finalizer_policy->generation; // 
if (prev.get_active_finalizer_policy_generation(latest_qc_claim_block_num).active_finalizer_policy_generation != active_generation_num) {
   next_header_state.latest_qc_claim_block_active_finalizer_policy = prev.get_finalizer_policies(latest_qc_claim_block_num).active_finalizer_policy;
} else {
   next_header_state.latest_qc_claim_block_active_finalizer_policy = nullptr;
}
```

With the appropriate information now in the new `block_header_state`, the code at the end of `verify_proper_block_exts` that verifies the attached QC should be modified to grab the necessary data from the `block_header_state` of the parent block rather than looking up the claimed block in the fork database. This may require computing the necessary weak digest of the claimed block on the fly from the finality digest found within the `finality_core`.

The two test cases described in the Problem section above should also be captured in test to verify these changes work.

#### Breaking change

Spring v1.0.0 has already been released with the existing structure of `block_header_state`. So changing the serialization of `block_header_state` would be a breaking change which impacts the serialized data format in the `fork_db.dat` and `chain_head.dat` files as well as in the v7 snapshots generated by Spring v1.0.0. 

Normally, we would not introduce such breaking changes in a patch release (or even a minor release), but the nature of this bug forces us to get the fix out sooner as a patch release. So we will be forced to break semver standards on this patch release and introduce the breaking change.

This means that the next release of Spring that includes this bug fix, assumed to be Spring v1.0.1, will not be able to start up normally using the state in the data directory processed by a Spring v1.0.0 (or earlier node). Starting from a snapshot will be required (or of course sync / replay from genesis is always an option).

So we should bump the version of the fork database with this change so that we can distinguish on startup between the new supported fork database and the old unsupported fork database. We can fail to startup with a meaningful error message if the fork database is on the old unsupported version.

There is still a possibility that the data directory contains no fork database but it includes a `chain_head.dat` file. This would be the case after starting from a snapshot but shutting down nodeos before it finishes replaying all of the irreversible blocks in the block log. So in that scenario, the `chain_head.dat` file could also be the old version. We do not have an official versioning scheme for the `chain_head.dat` file, but a variant is serialized to distinguish between the legacy (tag of 0) and Savanna (tag of 1) versions of the block state. So we could use that to detect that this is an old (unsupported) version of the `chain_head.dat` file and fail to startup with a meaningful error message. Additionally, we should use this opportunity to serialize the new `chain_head.dat` with version information for the future. However, we should pick a version scheme that make it unambiguous whether we are dealing with the new format or the old (v1.0.0) format.

There is no issue with starting up the Spring v1.0.1 node from v6 (or earlier) snapshot. But there is a catch with trying to start it with a v7 snapshot.

#### Problems with v7 snapshots

The problem with the v7 snapshot is that the `block_header_state` (not `block_header_state_legacy`) contained within may not have the necessary information expected by the v1.0.1 (or later) software. Particularly, it would be missing the active and pending generation numbers for past blocks (back to the block of the latest QC claim) and it would be missing any of those other relevant finalizer policies other than the active and pending one.

There are only limited circumstances in which this information can be reliably recovered despite not being in the snapshot:
+ If the snapshot is of a Legacy block, meaning a block prior to the start of the transition to Savanna, then there is no `block_header_state` to worry about at all.
+ If the snapshot is of a Transition block, then given how the consensus algorithm works, we know that the only finalizer policy that exists at that point is the genesis finalizer policy, which necessarily has a generation number of 1 and is necessarily tracked in the `block_header_state`, and furthermore all the transition blocks have no pending policy and have the genesis finalizer policy as their active finalizer policy.
+ If the snapshot is of a Proper Savanna block which still has an active finalizer policy with a generation of 1 and no pending finalizer policy, then we also know that `block_header_state` tracks all the necessary information.

Note that the first case of Legacy blocks means that it is always safe to startup with a v6 (or earlier) snapshot in v1.0.1 because v6 (or earlier) snapshots can only be taken on Legacy blocks.

Also note that some cases may appear to provide the necessary information to enable reliable recovery of the missing data in the new `block_header_state` but actually they do not.

For example, consider the case where the snapshot is of a block that has an active finalizer policy with a generation of 1 but it also had a pending finalizer policy. All finalizer policies that could be relevant to validating QCs going forward are in fact being tracked by the old `block_header_state` in that case. However, what is missing is whether or not a past block had that pending finalizer policy or had no finalizer policy. That single bit of information per each past block is unavailable in the old `block_header_state` and cannot be reliably recovered.

In cases where all information for the new `block_header_state` can be reliable recovered given a v7 snapshot, nodeos could allow loading from the v7 snapshot and automatically reconstructing the new `block_header_state` from the old `block_header_state` in the snapshot by filling in the missing information. But then that would mean that Spring v1.0.1 and later would only support loading v7 snapshots taken on blocks before the transition to Savanna or taken on blocks after the transition to Savanna but before the first proposed finalizer policy became pending (which would probably be not very long after the transition to Savanna happened).

To simplify both the changes in this issue and the explanation to users, we prefer to just disallow loading v7 snapshots going forward. Other than syncing/replaying from genesis, users will be forced to start a Spring v1.0.1 node using either a new v8 snapshot or the old v6 (or earlier) snapshots. But v7 snapshots would not be supported going forward.

Spring v1.0.1 would generate the new v8 snapshots that include the new `block_header_state` with all the necessary information.

##### Consensus protocol compatible

The solution requires making changes to the structure of `block_header_state`. But we intend to not change the consensus protocol with the changes required to fix the bug in this issue.

So it is important that the changes to `block_header_state` are done in a way that does not accidentally change how the `base_digest` or `reversible_blocks_mroot` are computed, or in general anything else that could break consensus protocol compatibility with Spring 1.0.0.

For `reversible_blocks_mroot` it should be easier to guarantee there is no change because `finality_core::get_reversible_blocks_mroot` constructs the `block_ref_digest_data` structs needed to compute the digest of each leaf node in the Merkle tree. So the structure of `block_ref_digest_data` should not change even though the `block_ref` struct will have more information in it.

But to guarantee `base_digest` does not change, specific changes are needed in `compute_base_digest`. Specifically, it is not longer okay to simply pack the `core` using the default serialization supported by the fc macros. A new serialization of `core` is needed specifically for use in `compute_base_digest` that preserves the serialization used in Spring 1.0.0.

To be confident that these changes have not accidentally changed the consensus protocol, a new test should be added to check for regression in consensus compatibility. 

The test could store a reference blockchain (with QCs) generated and serialized (and committed to the source control) at some earlier point in time. Then it could read that blockchain into a nodeos (replay it) and use it as a source of blocks from which another nodeos instance can sync those blocks. The test should involve both a replay and sync to test both of those code paths in `controller`.

We would not normally commit that reference blockchain to source control. The test/tool could allow us to manually regenerate it if necessary, but we would really only need to do it once (or whenever we want to change the nature of the reference blockchain for the test case). Then the test, when it normally runs, just ensures it can validate that blockchain. However, it would be good for the test to generate the reference blockchain anyway, even though it is going to throw it away under typical use, just as an ongoing check in our CI to ensure the reference blockchain generation portion of the test does not break or regress.

This test should ideally be done with the Boost testing framework so that the generation of the reference blockchain is deterministic, but an integration test is also acceptable. However, if we can guarantee the generation of the reference blockchain is deterministic, then it provides other advantages. First, anytime we need to change the reference blockchain (which remember is binary data committed to source control), a reviewer could easily validate the changed data in a pull request by regenerating it themself locally. Second, it allows for the test to include a final check at the end where it compares the block ID of the reference chain it generates to the one that was in the source control to ensure they are the same. 

With such a test implemented, to make sure we do not have an accidental consensus change as part of the work for this issue, it would be critical to generate the reference blockchain with the Spring implementation prior to the changes of this issue (e.g. using a branch built off of the Spring v1.0.0 tag with only this consensus regression test added on top). Then the test can act as a check that no accidental consensus change is introduced as one works on the changes required for this issue.

### PR DESCRIPTION
**Pull request by greg7mdp**
Resolves #694.

Implements updates described in issue #694:
  - store policy generation numbers in every `block_ref` of the `finality_core`
  - maintains `latest_qc_claim_block_active_finalizer_policy` in `block_header_state`
  - new snapshot format (`v8`) which adds these new members. `v7` format of spring 1.0  is unsupported.
  - new fork_database format (version 3). version 2 not loaded anymore, but version 1 (legacy fork_db only) OK.
  - update the serialization of the finalizer safety file, so it doesn't change even though the `block_ref` struct has two new members.
  - add version to `chain_head.dat` file and do not load existing version.
  - updated qc validation which does not require the fork database anymore, all needed info is in the parent `block_header_state`
  - add new test (`verify_spring_1_0_block_compatibitity`) validating that this PR's changes do not affect the block ids generated.
  - update tests impacted by the change, including adding to repo new snapshot v8 reference files.

### CODE REVIEW

File: libraries/chain/block_handle.cpp [hunk 1]
```diff
@@ -13,25 +23,34 @@ void block_handle::write(const std::filesystem::path& state_file) {
...
+   if (magic == chain_head_magic && version == chain_head_version) {
+      fc::raw::unpack(f, *this);
+      ilog("Loading chain_head block ${bn} ${id}", ("bn", block_num())("id", id()));
+      res = true;
+   }
 
    std::filesystem::remove(state_file);
 
-   return true;
+   return res;
```
Comment (heifner) [inline libraries/chain/block_handle.cpp:53]: If the `unpack` fails it throws an exception and the `chain_head.dat` is not removed. If the `chain_head.dat` is less than `2*sizeof(chain_head_magic)` it is not read but the file is not removed. If the magic or version is wrong which it will be for existing 1.0.0 `chain_head.dat`, the file is removed and then the error from `controller::startup` will be `No existing chain_head.dat file`.

Seems we should wrap the whole thing in a try-catch and consistently NOT remove the file. They could downgrade to 1.0.0, and be able to startup. 

I think we should report an error telling user to consider starting from a snapshot if this fails for any reason.

File: libraries/chain/block_header_state.cpp [hunk 2]
```diff
@@ -141,6 +141,61 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
...
+      assert(pending_finalizer_policy && pending_finalizer_policy->second->generation == pending_gen);
+      EOS_ASSERT(pending_finalizer_policy && pending_finalizer_policy->second->generation == pending_gen, chain_exception,
+                 "Logic error in finalizer policy retrieval");  // just in case
+      res.pending_finalizer_policy = pending_finalizer_policy->second;
+   }
+
+   return res;
+}
+
+// Only defined for core.latest_qc_claim().block_num <= num <= core.current_block_num()
```
Comment (heifner) [inline libraries/chain/block_header_state.cpp:187]: How about adding an `assert` of this.

File: libraries/chain/block_state.cpp [hunk 3]
```diff
@@ -233,7 +238,14 @@ vote_status_t block_state::has_voted(const bls_public_key& key) const {
...
 void block_state::verify_qc(const qc_t& qc) const {
-   aggregating_qc.verify_qc(qc, strong_digest, weak_digest);
+   // Do not use `block_state::aggregating_qc` which applies only for `this` block.
+   // `verify_qc()` can be called on a descendant `block_state` of `qc.block_num`, so we need
+   // to create a new `aggregating_qc_t` with the finalizer policies of the claimed block.
+   // ---------------------------------------------------------------------------------------
+   finalizer_policies_t policies = get_finalizer_policies(qc.block_num);
+   aggregating_qc_t aggregating_qc(policies.active_finalizer_policy, policies.pending_finalizer_policy);
+
+   aggregating_qc.verify_qc(qc, policies.finality_digest, create_weak_digest(policies.finality_digest));
```
Comment (heifner) [inline libraries/chain/block_state.cpp:248]: With this usage, probably makes sense to factor out qc verification out of `aggregating_qc_t` into another type that `aggregating_qc_t` and this can use. The `active_policy_sig` and `pending_policy_sig` of `aggregating_qc_t` are not used. Seems wasteful to create a `aggregating_qc_t` for this.

Maybe add a `finalizer_policy_pair_t` that both `aggregating_qc_t` and this method can use. The `finalizer_policy_pair_t` can have the `verify_qc` and `verify_dual_finalizers_votes` methods.

File: libraries/chain/controller.cpp [hunk 4]
```diff
@@ -2285,8 +2285,13 @@ struct controller_impl {
          } else {
             EOS_THROW(snapshot_exception, "Unsupported block_state version");
          }
+      } else if (header.version == 7) {
+         // snapshot created with Spring 1.0, which was very soon superseded by Spring 1.0.1
+         // and a new snapshot format.
+         // --------------------------------------------------------------------------------
+         EOS_THROW(snapshot_exception, "v7 snapshots are not supported anymore in Spring 1.01 and above");
```
Comment (heifner) [inline libraries/chain/controller.cpp:2292]: `1.0.1`

File: libraries/chain/block_state.cpp (hunk 3 above)
Comment (heifner) [reply libraries/chain/block_state.cpp:248]: Instead of `block_state` having a `verify_qc`, maybe it makes more sense for it to return a `finalizer_policy_pair_t` given a `block_num`.

File: libraries/chain/finality/finalizer.cpp [hunk 5]
```diff
@@ -267,7 +300,7 @@ void my_finalizers_t::load_finalizer_safety_info_v1(fsi_map& res) {
       bls_public_key pubkey;
       my_finalizers_t::fsi_t fsi;
       fc::raw::unpack(persist_file, pubkey);
-      fc::raw::unpack(persist_file, fsi);
+      unpack_v1(persist_file, fsi);
       res.emplace(pubkey, fsi);
```
Comment (heifner) [inline libraries/chain/finality/finalizer.cpp:304]: Why these safey.dat file changes? Just clean up or is there an actual change here?

File: libraries/chain/fork_database.cpp [hunk 6]
```diff
@@ -646,10 +646,16 @@ namespace eosio::chain {
...
-                                                   // version == 1 -> legacy
-                                                   // version == 2 -> savanna (two possible fork_db, one containing `block_state_legacy`,
-                                                   //                          one containing `block_state`)
+
+      // write out current version which is always max_supported_version
+      // version == 1 -> legacy
+      // version == 2 -> Spring 1.0
+      //                 (two possible fork_db, one containing `block_state_legacy`, one containing `block_state`)
+      //                  unsupported by Spring 1.01 and above
+      // version == 3 -> Spring 1.01 updated block_header_state (core with policy gen #)
```
Comment (heifner) [inline libraries/chain/fork_database.cpp:655]: `1.0.1`

File: libraries/chain/fork_database.cpp [hunk 7]
```diff
@@ -691,6 +697,8 @@ namespace eosio::chain {
 
             uint32_t version = 0;
             fc::raw::unpack( ds, version );
+            EOS_ASSERT( version != 2, fork_database_exception,
+                        "Version 2 of fork_database (created by Spring 1.0) is not supported" );
```
Comment (heifner) [inline libraries/chain/fork_database.cpp:701]: I think better to say `Spring 1.0.0`

File: unittests/snapshot_tests.cpp [hunk 8]
```diff
@@ -382,10 +382,10 @@ void compatible_versions_test()
    std::filesystem::copy(source_log_dir / "blocks.index", config.blocks_dir / "blocks.index");
    TESTER base_chain(config, *genesis);
 
-   std::string current_version = "v7";
+   std::string current_version = "v8";
 
    int ordinal = 0;
-   for(std::string version : {"v2", "v3", "v4" , "v5", "v6", "v7"})
+   for(std::string version : {"v2", "v3", "v4", "v5", "v6", "v8"}) // v7 version not supported in spring 1.01 and above
```
Comment (heifner) [inline unittests/snapshot_tests.cpp:388]: `1.0.1`

**Review by heifner — CHANGES_REQUESTED** [review]

File: libraries/chain/block_header_state.cpp [hunk 9]
```diff
@@ -141,6 +141,61 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
    return *active_finalizer_policy;
 }
 
+// Only defined for core.latest_qc_claim().block_num <= ref.block_num() <= core.current_block_num()
+// Retrieves the finalizer policies applicatble for the block referenced by `ref`.
+// See full explanation in issue #694.
+// ------------------------------------------------------------------------------------------------
+finalizer_policies_t block_header_state::get_finalizer_policies(const block_ref& ref) const {
```
Comment (linh2931) [inline libraries/chain/block_header_state.cpp:148]: The preconditions of this function can be asserted here like the asserts in `core`.

File: libraries/chain/block_header_state.cpp [hunk 10]
```diff
@@ -141,6 +141,61 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
...
+
+   if (active_finalizer_policy->generation == active_gen)
+      res.active_finalizer_policy = active_finalizer_policy;      // the one active at block_num is still active
+   else {
+      // cannot be the pending one as it never was active
+      assert(!pending_finalizer_policy || pending_finalizer_policy->second->generation > active_gen);
+
+      // has to be the one in latest_qc_claim_block_active_finalizer_policy
+      assert(latest_qc_claim_block_active_finalizer_policy != nullptr);
+      assert(latest_qc_claim_block_active_finalizer_policy->generation == active_gen);
```
Comment (linh2931) [inline libraries/chain/block_header_state.cpp:164]: Since EOS_ASSERT on line 164 is always on, is this small assert redundant?

File: libraries/chain/block_header_state.cpp [hunk 11]
```diff
@@ -141,6 +141,61 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
...
+
+   auto pending_gen = ref.pending_policy_generation;
+   if (pending_gen == 0)
+      res.pending_finalizer_policy = nullptr;                    // no pending policy at block_num.
+   else if (pending_gen == active_finalizer_policy->generation)
+      res.pending_finalizer_policy = active_finalizer_policy;    // policy pending at block_num became active
+   else {
+      // cannot be the one in latest_qc_claim_block_active_finalizer_policy since it was active at
+      // core.latest_qc_claim().block_num. So it must be the one still pending.
+      assert(pending_finalizer_policy && pending_finalizer_policy->second->generation == pending_gen);
```
Comment (linh2931) [inline libraries/chain/block_header_state.cpp:178]: Is this small assert redundant?

File: libraries/chain/block_header_state.cpp [hunk 12]
```diff
@@ -141,6 +141,61 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
...
+}
+
+// Only defined for core.latest_qc_claim().block_num <= num <= core.current_block_num()
+// Retrieves the active finalizer policy generation applicatble for the block `num`, which
+// can be the current block or one of its ancestors up to core.latest_qc_claim().block_num (incl).
+// -----------------------------------------------------------------------------------------------
+uint32_t block_header_state::get_active_finalizer_policy_generation(block_num_type num) const {
+   if (num == block_num())
+      return active_finalizer_policy->generation;
+   const block_ref& ref = core.get_block_reference(num);
```
Comment (linh2931) [inline libraries/chain/block_header_state.cpp:194]: Can we assert `get_block_reference(num)` always find the block_ref for the `num`?

File: libraries/chain/block_header_state.cpp [hunk 13]
```diff
@@ -325,6 +380,22 @@ void finish_next(const block_header_state& prev,
       next_header_state.finalizer_policy_generation = prev.finalizer_policy_generation;
    }
 
+   // now populate next_header_state.latest_qc_claim_block_active_finalizer_policy
+   // this keeps track of the finalizer policy which was active @ latest_qc_claim().block_num, but which
+   // can be overwritten by a previously pending police (member `active_finalizer_policy`)
```
Comment (linh2931) [inline libraries/chain/block_header_state.cpp:385]: police -> policy

File: libraries/chain/block_header_state.cpp [hunk 14]
```diff
@@ -325,6 +380,22 @@ void finish_next(const block_header_state& prev,
...
+   // --------------------------------------------------------------------------------------------------
+   const auto& next_core                 = next_header_state.core;
+   auto        latest_qc_claim_block_num = next_core.latest_qc_claim().block_num;
+   const auto  active_generation_num     = next_header_state.active_finalizer_policy->generation;
+   if (prev.get_active_finalizer_policy_generation(latest_qc_claim_block_num) != active_generation_num) {
+      const auto& latest_qc_claim_block_ref = next_header_state.core.get_block_reference(latest_qc_claim_block_num);
+      next_header_state.latest_qc_claim_block_active_finalizer_policy =
+         prev.get_finalizer_policies(latest_qc_claim_block_ref).active_finalizer_policy;
+   } else {
+      next_header_state.latest_qc_claim_block_active_finalizer_policy = nullptr;
```
Comment (linh2931) [inline libraries/chain/block_header_state.cpp:396]: why set to `nullptr`?

**Review by linh2931 — COMMENTED** [review]
Submit partial reviews. Will continue the rest shortly.

File: libraries/chain/block_handle.cpp (hunk 1 above)
Comment (greg7mdp) [reply libraries/chain/block_handle.cpp:61]: done.

File: libraries/chain/block_header_state.cpp (hunk 2 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:189]: done.

File: libraries/chain/block_state.cpp (hunk 3 above)
Comment (greg7mdp) [reply libraries/chain/block_state.cpp:248]: I don't disagree, but I think we should refrain from refactoring the code in a 1.01 release. 
I tried to do what was necessary for cleany fixing the issue in this PR.
I'll be happy to clean up this further in a separate PR targeted to the main branch.

File: libraries/chain/finality/finalizer.cpp (hunk 5 above)
Comment (greg7mdp) [reply libraries/chain/finality/finalizer.cpp:304]: Not a cleanup. We cannot use the `fc::raw::unpack(persist_file, fsi);` because the `fsi` includes `last_vote` and `lock`, which are of type `block_ref`, and `block_ref` now includes two new members (the active and pending generations)

File: libraries/chain/fork_database.cpp (hunk 6 above)
Comment (greg7mdp) [reply libraries/chain/fork_database.cpp:655]: updated.

File: libraries/chain/fork_database.cpp (hunk 7 above)
Comment (greg7mdp) [reply libraries/chain/fork_database.cpp:701]: updated

File: unittests/snapshot_tests.cpp (hunk 8 above)
Comment (greg7mdp) [reply unittests/snapshot_tests.cpp:388]: updated.

File: libraries/chain/block_handle.cpp [hunk 15]
```diff
@@ -4,6 +4,16 @@
 
 namespace eosio::chain {
 
+// -------------------------------------------------------------------------------------------
+// prior to writing magic and version numbers, we simply serialized the class (*this) to
+// file. Let's call this the implicit version 0, which is not supported anymore in
+// Spring 1.01 and above.
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_handle.cpp:10]: updated.

File: libraries/chain/block_handle.cpp [hunk 16]
```diff
@@ -4,6 +4,16 @@
...
+// However, we need to make sure that `chain_head_magic` can't match the tag of a std::variant
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_handle.cpp:11]: [this one](https://github.com/AntelopeIO/spring/blob/43e7ab54332336a0188aa5a0871cf9263569365e/libraries/chain/include/eosio/chain/block_handle.hpp#L13)

File: libraries/chain/block_handle.cpp [hunk 17]
```diff
@@ -13,25 +23,34 @@ void block_handle::write(const std::filesystem::path& state_file) {
...
+   fc::raw::pack(f, chain_head_version);
    fc::raw::pack(f, *this);
 }
 
 bool block_handle::read(const std::filesystem::path& state_file) {
-   if (!std::filesystem::exists(state_file))
-      return false;
+   bool res = false;
+
+   if (!std::filesystem::exists(state_file) || std::filesystem::file_size(state_file) <= 2 * sizeof(chain_head_magic))
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_handle.cpp]: I have an EOS_ASSERT now.

File: libraries/chain/block_header_state.cpp (hunk 9 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:148]: I added the assert.

File: libraries/chain/block_header_state.cpp (hunk 10 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:166]: No, I have both on purpose.
The `assert` to clearly state this property always hold. 
The `EOS_ASSERT` in case I am wrong  and that is not true. Which is why I added the comment `// just in case`.

File: libraries/chain/block_header_state.cpp (hunk 11 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:180]: No, I have both on purpose.
The assert to clearly state this property always hold. And the fact that this small `assert`  is there indicates that the property holds in all our tests.

The EOS_ASSERT in case I am wrong and that is not true. Which is why I added the comment // just in case.

**Comment by ericpassmore** [comment]
Note:start
category: Other
component: Internal
summary: Enhance Block Header State and only use provided block data to verify QC claims.
Note:end

File: libraries/chain/block_header_state.cpp (hunk 12 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:198]: `get_block_reference` returns a referencem, and already has the following asserts:

```
   assert(last_final_block_num() <= block_num); // Satisfied by precondition.
   assert(block_num < current_block_num()); // Satisfied by precondition.
```

Because the assert I added at the start of the function is stricter, I think we're fine.

File: libraries/chain/block_header_state.cpp (hunk 13 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:389]: updated.

File: libraries/chain/block_header_state.cpp (hunk 14 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:400]: We reset it when it doesn't need to be tracked anymore. This will allow the memory holding that policy to be release when the last block holding it as an active policy is also removed from fork_db.

File: libraries/chain/include/eosio/chain/block_header_state.hpp [hunk 18]
```diff
@@ -121,12 +129,22 @@ struct block_header_state : fc::reflect_init {
...
    std::vector<std::pair<block_num_type, finalizer_policy_ptr>> proposed_finalizer_policies;
+
    // Track in-flight pending finalizer policy. At most one pending
    // finalizer policy at any moment.
    // When the block associated with the pending finalizer policy becomes final,
    // it becomes active.
    std::optional<std::pair<block_num_type, finalizer_policy_ptr>> pending_finalizer_policy;
 
+   // It may be that the `finality_core` references a finalizer policy generation which is neither the active
+   // or pending one. This can happen when a pending policy became active, replacing the previously active
```
Comment (arhag) [inline libraries/chain/include/eosio/chain/block_header_state.hpp:140]: To be clear, it is possible for the latest final block (which also is tracked in  `finality_core` to have an active finalizer policy that is still not being tracked.

But we don't care about that.

We just care about any finalizer policies tracked within `finality_core` that are restricted to the block range from `core.latest_qc_claim().block_num` to `core.current_block_num()` inclusive.

File: libraries/chain/block_header_state.cpp [hunk 19]
```diff
@@ -141,6 +141,65 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
    return *active_finalizer_policy;
 }
 
+// Only defined for core.latest_qc_claim().block_num <= ref.block_num() <= core.current_block_num()
+// Retrieves the finalizer policies applicatble for the block referenced by `ref`.
```
Comment (arhag) [inline libraries/chain/block_header_state.cpp:145]: Typo: applicable

File: libraries/chain/block_header_state.cpp [hunk 20]
```diff
@@ -141,6 +141,65 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
...
+   if (active_finalizer_policy->generation == active_gen)
+      res.active_finalizer_policy = active_finalizer_policy;      // the one active at block_num is still active
+   else {
+      // cannot be the pending one as it never was active
+      assert(!pending_finalizer_policy || pending_finalizer_policy->second->generation > active_gen);
+
+      // has to be the one in latest_qc_claim_block_active_finalizer_policy
+      assert(latest_qc_claim_block_active_finalizer_policy != nullptr);
+      assert(latest_qc_claim_block_active_finalizer_policy->generation == active_gen);
+      EOS_ASSERT(latest_qc_claim_block_active_finalizer_policy->generation == active_gen, chain_exception,
```
Comment (arhag) [inline libraries/chain/block_header_state.cpp:167]: Should be consistent with the asserts above.

This should never happen, but if we somehow are wrong and it does, we would like to avoid the undefined behavior. 

So the condition for the `EOS_ASSERT` should be: `latest_qc_claim_block_active_finalizer_policy != nullptr && latest_qc_claim_block_active_finalizer_policy->generation == active_gen`.

File: unittests/snapshot_tests.cpp [hunk 21]
```diff
@@ -382,10 +382,10 @@ void compatible_versions_test()
    std::filesystem::copy(source_log_dir / "blocks.index", config.blocks_dir / "blocks.index");
    TESTER base_chain(config, *genesis);
 
-   std::string current_version = "v7";
+   std::string current_version = "v8";
 
    int ordinal = 0;
-   for(std::string version : {"v2", "v3", "v4" , "v5", "v6", "v7"})
+   for(std::string version : {"v2", "v3", "v4", "v5", "v6", "v8"}) // v7 version not supported in spring 1.0.1 and above
```
Comment (arhag) [inline unittests/snapshot_tests.cpp:388]: Capitalize Spring.

Comment (arhag) [reply unittests/snapshot_tests.cpp:388]: Also, maybe change the example in the comment below of how to support a new snapshot version in this test to use `snap_v8` instead of `snap_v7`.

File: unittests/snapshots/CMakeLists.txt [hunk 22]
```diff
@@ -23,3 +23,7 @@ configure_file( ${CMAKE_CURRENT_SOURCE_DIR}/snap_v6.bin.json.gz ${CMAKE_CURRENT_
 configure_file( ${CMAKE_CURRENT_SOURCE_DIR}/snap_v7.bin.gz ${CMAKE_CURRENT_BINARY_DIR}/snap_v7.bin.gz COPYONLY )
 configure_file( ${CMAKE_CURRENT_SOURCE_DIR}/snap_v7.json.gz  ${CMAKE_CURRENT_BINARY_DIR}/snap_v7.json.gz  COPYONLY )
 configure_file( ${CMAKE_CURRENT_SOURCE_DIR}/snap_v7.bin.json.gz ${CMAKE_CURRENT_BINARY_DIR}/snap_v7.bin.json.gz COPYONLY )
```
Comment (arhag) [inline unittests/snapshots/CMakeLists.txt:25]: Should we get rid of the `snap_v7` files now?

File: unittests/savanna_misc_tests.cpp [hunk 23]
```diff
@@ -537,9 +535,10 @@ BOOST_FIXTURE_TEST_CASE(validate_qc_requiring_finalizer_policies, savanna_cluste
    BOOST_REQUIRE_EQUAL(active->generation, p2);         // b6 has active finalizer policy p2
    BOOST_REQUIRE(!A.head_pending_finalizer_policy());   // and no pending finalizer policy.
 
-   auto b6_snapshot = A.snapshot();
+   // At this point, in the Spring 1.0 implementation, policy  P2 is lost from the block_header_state
```
Comment (arhag) [inline unittests/savanna_misc_tests.cpp:538]: Should say `in the Spring 1.0.0 implementation (which has the bug described in issue #694)`.

File: unittests/savanna_misc_tests.cpp [hunk 24]
```diff
@@ -585,12 +584,107 @@ BOOST_FIXTURE_TEST_CASE(validate_qc_requiring_finalizer_policies, savanna_cluste
...
-#endif
+
+} FC_LOG_AND_RETHROW()
+
+
+
+// ---------------------------------------------------------------------------------------------------
+// For issue #694, we need to change the finality core of the `block_header_state`, but we want to
+// insure that this doesn't create a consensus incompatibility with spring 1.0, so the blocks created
+// with newer versions remain compatible (and linkable) by spring 1.0.
```
Comment (arhag) [inline unittests/savanna_misc_tests.cpp:599]: `insure` -> `ensure`
`spring 1.0` -> `Spring 1.0.0` (in two places)

File: unittests/savanna_misc_tests.cpp [hunk 25]
```diff
@@ -585,12 +584,107 @@ BOOST_FIXTURE_TEST_CASE(validate_qc_requiring_finalizer_policies, savanna_cluste
...
+   push_block(0, b8);                                   // nodes received b6
+
+   auto b9 = A.produce_block();
+   print("b9", b9);
+   BOOST_REQUIRE_EQUAL(qc_s(qc(b9)), strong_qc(b8));    // b9 claims a strong QC on b8
+   BOOST_REQUIRE_EQUAL(A.lib_number, b6->block_num());  // b9 makes B6 final
+
+   // check that the block id of b9 match what we got with spring 1.0
+   auto b9_id = b9->calculate_id();
+   BOOST_REQUIRE_EQUAL(b9_id, block_id_type{"00000013725f3d79bd4dd4091d0853d010a320f95240981711a942673ad87918"});
```
Comment (arhag) [inline unittests/savanna_misc_tests.cpp:687]: This is okay for now. But not quite what was requested in https://github.com/AntelopeIO/spring/issues/694.

The goal for this test was to commit the blocks generated by Spring 1.0.0 to the repo and then have the test successfully synchronize the blocks. That way if there was a problem, the error would help us reveal where the problem was. And we could always step-through debug to get the bottom of the issue.

With this approach we just detect something is wrong but the test does not permit us to figure out what could be the cause.

Anyway, you do not need to do what was originally requested as part of this issue. This achieves the goal of detecting unintentional consensus changes. I created a new issue https://github.com/AntelopeIO/spring/issues/742 to track the further work needed to augment this test, and that work can go to `main` instead.

**Review by arhag — CHANGES_REQUESTED** [review]
By the way, your PR description says "all needed info is in the root `block_header_state`" but it should say "all needed info is in the parent `block_header_state`".

File: libraries/chain/block_handle.cpp [hunk 26]
```diff
@@ -13,24 +23,39 @@ void block_handle::write(const std::filesystem::path& state_file) {
...
 
 bool block_handle::read(const std::filesystem::path& state_file) {
    if (!std::filesystem::exists(state_file))
       return false;
 
-   fc::datastream<fc::cfile> f;
-   f.set_file_path(state_file);
-   f.open("rb");
+   EOS_ASSERT(std::filesystem::file_size(state_file) >= 2 * sizeof(chain_head_magic), chain_exception,
+              "File `chain_head.dat` seems to be corrupted. The best course of action might be to restart from a snapshot (v8 or above)" );
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_handle.cpp:36]: https://github.com/AntelopeIO/spring/pull/719/commits/008e1e5b6

File: libraries/chain/block_handle.cpp [hunk 27]
```diff
@@ -13,24 +23,39 @@ void block_handle::write(const std::filesystem::path& state_file) {
...
 
-   ilog("Loading chain_head block ${bn} ${id}", ("bn", block_num())("id", id()));
+      uint64_t magic, version;
+      fc::raw::unpack(f, magic);
+      fc::raw::unpack(f, version);
 
-   std::filesystem::remove(state_file);
+      EOS_ASSERT(magic == chain_head_magic && version == chain_head_version, chain_exception,
+                 "Error reading `chain_head.dat` file. It is likely a Spring 1.0 version which is not supported by Spring 1.01 and above"
+                 "The best course of action might be to restart from a snapshot (v8 or above)" );
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_handle.cpp]: https://github.com/AntelopeIO/spring/pull/719/commits/008e1e5b6

File: libraries/chain/block_state.cpp [hunk 28]
```diff
@@ -184,25 +184,30 @@ block_state_ptr block_state::create_transition_block(
    return result_ptr;
 }
 
-block_state::block_state(snapshot_detail::snapshot_block_state_v7&& sbs)
+// Spring 1.01 to ? snapshot v8 format. Updated `finality_core` to include finalizer policies
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_state.cpp:187]: https://github.com/AntelopeIO/spring/pull/719/commits/e3cdb7c8127968243dd824f66a392d0e3456aa2b

File: libraries/chain/fork_database.cpp [hunk 29]
```diff
@@ -646,10 +646,16 @@ namespace eosio::chain {
...
-      fc::raw::pack( out, max_supported_version ); // write out current version which is always max_supported_version
-                                                   // version == 1 -> legacy
-                                                   // version == 2 -> savanna (two possible fork_db, one containing `block_state_legacy`,
-                                                   //                          one containing `block_state`)
+
+      // write out current version which is always max_supported_version
+      // version == 1 -> legacy
+      // version == 2 -> Spring 1.0.0
+      //                 (two possible fork_db, one containing `block_state_legacy`, one containing `block_state`)
+      //                  unsupported by Spring 1.01 and above
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/fork_database.cpp]: https://github.com/AntelopeIO/spring/pull/719/commits/e3cdb7c8127968243dd824f66a392d0e3456aa2b

File: libraries/chain/controller.cpp [hunk 30]
```diff
@@ -2291,8 +2291,13 @@ struct controller_impl {
          } else {
             EOS_THROW(snapshot_exception, "Unsupported block_state version");
          }
+      } else if (header.version == 7) {
+         // snapshot created with Spring 1.0, which was very soon superseded by Spring 1.0.1
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/controller.cpp:2295]: https://github.com/AntelopeIO/spring/pull/719/commits/fa686db91f87c71ea08255f6a194b3c8587ada42

File: libraries/chain/include/eosio/chain/block_header_state.hpp [hunk 31]
```diff
@@ -192,6 +213,10 @@ struct block_header_state : fc::reflect_init {
    const finalizer_policy& get_last_pending_finalizer_policy() const;
    const proposer_policy& get_last_proposed_proposer_policy() const;
 
+   // Only defined for core.latest_qc_claim().block_num <= num <= core.current_block_num()
+   finalizer_policies_t get_finalizer_policies(const block_ref& ref) const;
+   uint32_t get_active_finalizer_policy_generation(block_num_type block_num) const;
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/block_header_state.hpp:218]: https://github.com/AntelopeIO/spring/pull/719/commits/43622f20d47511d7e70b27c76e429ca2cf794326

File: libraries/chain/include/eosio/chain/block_state.hpp [hunk 32]
```diff
@@ -178,9 +182,15 @@ struct block_state : public block_header_state {     // block_header_state provi
          bool                              skip_validate_signee,
          const std::optional<digest_type>& action_mroot_savanna);
 
-   explicit block_state(snapshot_detail::snapshot_block_state_v7&& sbs);
+   explicit block_state(snapshot_detail::snapshot_block_state_v8&& sbs);
 
    void sign(const signer_callback_type& signer, const block_signing_authority& valid_block_signing_authority);
+
+   finalizer_policies_t get_finalizer_policies(block_num_type num) const {
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/block_state.hpp:189]: https://github.com/AntelopeIO/spring/pull/719/commits/43622f20d47511d7e70b27c76e429ca2cf794326

File: libraries/chain/block_header_state.cpp [hunk 33]
```diff
@@ -141,6 +141,65 @@ const finalizer_policy& block_header_state::get_last_pending_finalizer_policy()
...
+   return res;
+}
+
+// Only defined for core.latest_qc_claim().block_num <= num <= core.current_block_num()
+// Retrieves the active finalizer policy generation applicatble for the block `num`, which
+// can be the current block or one of its ancestors up to core.latest_qc_claim().block_num (incl).
+// -----------------------------------------------------------------------------------------------
+uint32_t block_header_state::get_active_finalizer_policy_generation(block_num_type num) const {
+   assert(core.links.empty() ||   // called from a bogus block_state constructed in a test
+          (core.latest_qc_claim().block_num <= num && num <= core.current_block_num()));
```
[the remark this answers is not in the document]
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:195]: https://github.com/AntelopeIO/spring/pull/719/commits/4164a34b1f15871df1885844128842619d023dec

File: libraries/chain/include/eosio/chain/block_header_state.hpp (hunk 18 above)
Comment (greg7mdp) [reply libraries/chain/include/eosio/chain/block_header_state.hpp:140]: https://github.com/AntelopeIO/spring/pull/719/commits/0dd7a3639f78f350fae5bcf7ecbaa20972337226

File: libraries/chain/block_header_state.cpp (hunk 19 above)
Comment (greg7mdp) [reply libraries/chain/block_header_state.cpp:145]: https://github.com/AntelopeIO/spring/pull/719/commits/ced3e553b6a4b0500bc80efb05ae6c781e24c641

File: unittests/snapshot_tests.cpp (hunk 21 above)
Comment (greg7mdp) [reply unittests/snapshot_tests.cpp:388]: https://github.com/AntelopeIO/spring/pull/719/commits/edf294dee52b5f314bab2a52928de9d2a06a1eb6

File: unittests/snapshots/CMakeLists.txt (hunk 22 above)
Comment (greg7mdp) [reply unittests/snapshots/CMakeLists.txt:25]: https://github.com/AntelopeIO/spring/pull/719/commits/1bdd27645b5ab83eaa630970d9ccc55e7241d2f8

File: libraries/chain/block_state.cpp (hunk 3 above)
Comment (heifner) [reply libraries/chain/block_state.cpp:248]: Please create an issue for it if not doing it in this PR. It is wasteful as is.

File: unittests/savanna_misc_tests.cpp (hunk 24 above)
Comment (greg7mdp) [reply unittests/savanna_misc_tests.cpp:599]: https://github.com/AntelopeIO/spring/pull/719/commits/d272c2517ef206052e74fb9bec037c073e6d5be7

File: unittests/savanna_misc_tests.cpp (hunk 23 above)
Comment (greg7mdp) [reply unittests/savanna_misc_tests.cpp:538]: https://github.com/AntelopeIO/spring/pull/719/commits/d272c2517ef206052e74fb9bec037c073e6d5be7

File: libraries/chain/controller.cpp (hunk 4 above)
Comment (greg7mdp) [reply libraries/chain/controller.cpp]: https://github.com/AntelopeIO/spring/pull/719/commits/43e7ab54332336a0188aa5a0871cf9263569365e

File: libraries/chain/include/eosio/chain/block_state.hpp [hunk 34]
```diff
@@ -127,7 +127,11 @@ struct block_state : public block_header_state {     // block_header_state provi
       return timestamp() > fc::time_point::now() - fc::seconds(30);
    }
 
-   block_ref make_block_ref() const { return block_ref{block_id, timestamp(), strong_digest }; } // use the cached `finality_digest`
+   // use the cached `finality_digest`
+   block_ref make_block_ref() const {
```
Comment (linh2931) [inline libraries/chain/include/eosio/chain/block_state.hpp:131]: Why do we define a new `make_block_ref` here? We already have one in block_header_state.

**Review by heifner — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]
