### PR TITLE
PH: Change default transaction generator trx expiration

### LINKED ISSUE #1093: Test: Transaction Expiration Too Far
The `ship_streamer_test.py` (and maybe others) passes `testTrxGenDurationSec=60*60` which it appears the trx_generator uses for expiration of transactions. This can cause the transactions to fail.

```
debug 2025-01-07T01:04:05.672 nodeos    producer_plugin.cpp:2464      log_trx_results      ] [TRX_TRACE] Speculative execution is REJECTING tx: fe541e095fff347226ff7a9dd450dcffc925aba0ad1c7d6f5de724733d5014a6, auth: defproducera : action: eosio:transfer, Transaction expiration is too far in the future relative to the reference time of 2025-01-07T01:04:00.000, expiration is 2025-01-07T02:04:05 and the maximum transaction lifetime is 3600 seconds
debug 2025-01-07T01:04:05.672 nodeos    producer_plugin.cpp:2467      log_trx_results      ] [TRX_TRACE] Speculative execution is REJECTING tx: {"expiration":"2025-01-07T02:04:05","ref_block_num":74,"ref_block_prefix":825951873,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[{"account":"eosio.null","name":"nonce","authorization":[],"data":{"size":41,"hex":"28303a333a373435363937333039333230323832313132333a31373336323131383435363731333137"},"hex_data":{"size":41,"hex":"28303a333a373435363937333039333230323832313132333a31373336323131383435363731333137"}}],"actions":[{"account":"eosio","name":"transfer","authorization":[{"actor":"defproducera","permission":"active"}],"data":{"size":36,"hex":"60ae423ad15b974a70ae423ad15b974a1027000000000000044355520000000003363036"},"hex_data":{"size":36,"hex":"60ae423ad15b974a70ae423ad15b974a1027000000000000044355520000000003363036"}}]} 
debug 2025-01-07T01:04:05.672 nodeos    producer_plugin.cpp:2470      log_trx_results      ] [TRX_TRACE] Speculative execution is REJECTING tx: {"id":"fe541e095fff347226ff7a9dd450dcffc925aba0ad1c7d6f5de724733d5014a6","block_num":123,"block_time":"2025-01-07T01:04:00.000","producer_block_id":null,"receipt":null,"elapsed":161,"net_usage":0,"scheduled":false,"action_traces":[],"account_ram_delta":null,"except":{"code":3040006,"name":"tx_exp_too_far_exception","message":"Transaction Expiration Too Far","stack":[{"context":{"level":"error","file":"controller.cpp","line":5845,"method":"validate_expiration","hostname":"","thread_name":"nodeos","timestamp":"2025-01-07T01:04:05.671"},"format":"Transaction expiration is too far in the future relative to the reference time of ${reference_time}, expiration is ${trx.expiration} and the maximum transaction lifetime is ${max_til_exp} seconds","data":{"trx.expiration":"2025-01-07T02:04:05","reference_time":"2025-01-07T01:04:00.000","max_til_exp":3600}},{"context":{"level":"warn","file":"controller.cpp","line":5846,"method":"validate_expiration","hostname":"","thread_name":"nodeos","timestamp":"2025-01-07T01:04:05.671"},"format":"","data":{"trx":{"expiration":"2025-01-07T02:04:05","ref_block_num":74,"ref_block_prefix":825951873,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[{"account":"eosio.null","name":"nonce","authorization":[],"data":"28303a333a373435363937333039333230323832313132333a31373336323131383435363731333137"}],"actions":[{"account":"eosio","name":"transfer","authorization":[{"actor":"defproducera","permission":"active"}],"data":"60ae423ad15b974a70ae423ad15b974a1027000000000000044355520000000003363036"}],"transaction_extensions":[]}}}]},"error_code":"10000000000000000000"} 
debug 2025-01-07T01:04:05.672 nodeos    net_plugin.cpp:3825           operator()           ] bad packed_transaction : Transaction Expiration Too Far
debug 2025-01-07T01:04:05.672 net-1     net_plugin.cpp:4108           operator()           ] signaled NACK, trx-id = fe541e095fff347226ff7a9dd450dcffc925aba0ad1c7d6f5de724733d5014a6 : 3040006 tx_exp_too_far_exception: Transaction Expiration Too Far
Transaction expiration is too far in the future relative to the reference time of 2025-01-07T01:04:00.000, expiration is 2025-01-07T02:04:05 and the maximum transaction lifetime is 3600 seconds
    {"trx.expiration":"2025-01-07T02:04:05","reference_time":"2025-01-07T01:04:00.000","max_til_exp":3600}
    nodeos  controller.cpp:5845 validate_expiration

    {"trx":{"expiration":"2025-01-07T02:04:05","ref_block_num":74,"ref_block_prefix":825951873,"max_net_usage_words":0,"max_cpu_usage_ms":0,"delay_sec":0,"context_free_actions":[{"account":"eosio.null","name":"nonce","authorization":[],"data":"28303a333a373435363937333039333230323832313132333a31373336323131383435363731333137"}],"actions":[{"account":"eosio","name":"transfer","authorization":[{"actor":"defproducera","permission":"active"}],"data":"60ae423ad15b974a70ae423ad15b974a1027000000000000044355520000000003363036"}],"transaction_extensions":[]}}
    nodeos  controller.cpp:5846 validate_expiration

debug 2025-01-07T01:04:05.672 net-1     net_plugin.cpp:2811           rejected_transaction ] not sending rejected transaction fe541e095fff347226ff7a9dd450dcffc925aba0ad1c7d6f5de724733d5014a6
```

### PR DESCRIPTION
**Pull request by heifner**
The transaction generator, used in performance testing, default transaction expiration was set to 60 minutes. 60 minutes is the also the default maximum transaction expiration limit. Since the comparison is `<= pending_block_time` this can fail.

Changed the default to 30 minutes which is more than enough. Seems, any performance test that takes 30 minutes to get a transaction to execute should be considered a failure.

https://github.com/AntelopeIO/spring/blob/8cc52d9ad51e2f03f144d8de9afbcfb1476b4563/libraries/chain/controller.cpp#L5840-L5840

Resolves #1093

### CODE REVIEW

File: tests/trx_generator/main.cpp [hunk 1]
```diff
@@ -28,7 +28,7 @@ int main(int argc, char** argv) {
    et::accounts_config accts_config;
    et::trx_tps_tester_config tester_config;
 
-   const int64_t trx_expiration_max = 3600;
+   const int64_t trx_expiration_max = 3599;
```
Comment (greg7mdp) [inline tests/trx_generator/main.cpp:31]: why 3599?

Comment (heifner) [reply tests/trx_generator/main.cpp:31]: The default on-chain limit is 3600 and the comparison is `<= pending_block_time`. This should prevent someone specifying 3600 and hitting that limit. Although, since that is an on-chain configurable value, maybe `trx_generator` should not have any hard-coded max.

**Comment by ericpassmore** [comment]
Note:start
category: Tests
component: Performance Harness
summary: Decrease transaction expiration to more reasonable 30 minutes. 
Note:end

**Review by greg7mdp — APPROVED** [review]

**Review by spoonincode — APPROVED** [review]
