### PR TITLE
[1.0-beta4] P2P: Fix fork check on connection

### LINKED ISSUE #456: beta4 testnet - finalizer not voting
- Started without a safety.dat file
```
error 2024-07-31T15:33:51.862 nodeos    finalizer.cpp:218             load_finalizer_safet ] unable to open finalizer safety persistence file /opt/SLOWtestNet/finalizers/safety.dat, file doesn't exist
```

- Synced through transition
```
info  2024-07-31T15:33:55.216 net-3     net_plugin.cpp:2183           operator()           ] ["slownet.eosusa.io:19883 - 42b454f" - 2 10.10.10.116:19883] requesting range 30602 to 30801, fhead 30434, lib 30090
info  2024-07-31T15:33:55.233 nodeos    controller.cpp:1360           transition_to_savann ] Transitioning to savanna, IF Genesis Block 30275, IF Critical Block 30607
info  2024-07-31T15:33:55.305 nodeos    controller.cpp:1405           operator()           ] Transition to instant finality happening after block 30607, First IF Proper Block 30608
info  2024-07-31T15:33:55.306 nodeos    producer_plugin.cpp:688       on_block             ] Block 19068e4ffe4f3b17... #30608 @ 2024-07-29T15:22:24.500 produced by pythoncolors, latency: 173490806ms has no votes
```

- Producer/finalizer became active
```
info  2024-07-31T18:16:10.658 nodeos    controller.cpp:3231           operator()           ] Scheduling proposer schedule change at 2024-07-31T18:16:18.000: {"version":5,"producers":[{"producer_name":"batinthedark","authority":[0,{"threshold":1,"keys":[{"key":"EOS6dwoM8XGMQn49LokUcLiony7JDkbHrsFDvh5svLvPDkXtvM7oR","weight":1}]}]},{"producer_name":"bighornsheep","authority":[0,{"threshold":1,"keys":[{"key":"EOS5xfwWr4UumKm4PqUGnyCrFWYo6j5cLioNGg5yf4GgcTp2WcYxf","weight":1}]}]},{"producer_name":"bigpolarbear","authority":[0,{"threshold":1,"keys":[{"key":"EOS6oZi9WjXUcLionUtSiKRa4iwCW5cT6oTzoWZdENXq1p2pq53Nv","weight":1}]}]},{"producer_name":"clevermonkey","authority":[0,{"threshold":1,"keys":[{"key":"EOS5mp5wmRyL5RH2JUeEh3eoZxkJ2ZZJ9PVd1BcLioNuq4PRCZYxQ","weight":1}]}]},{"producer_name":"dumpsterfire","authority":[0,{"threshold":1,"keys":[{"key":"EOS6GXEcfsGD3z3jQ7SZfGZ26UJLabhGc7DtqRLMCMgfcYQzZSoJX","weight":1}]}]},{"producer_name":"funnyhamster","authority":[0,{"threshold":1,"keys":[{"key":"EOS7A9BoRetjpKtE3sqA6HRykRJ955MjQ5XdRmCLionVte2uERL8h","weight":1}]}]},{"producer_name":"gorillapower","authority":[0,{"threshold":1,"keys":[{"key":"EOS8X5NCx1Xqa1xgQgBa9s6EK7M1SjGaDreAcLion4kDVLsjhQr9n","weight":1}]}]},{"producer_name":"hippopotamus","authority":[0,{"threshold":1,"keys":[{"key":"EOS7qDcxm8YtAZUA3t9kxNGuzpCLioNnzpTRigi5Dwsfnszckobwc","weight":1}]}]},{"producer_name":"hungryolddog","authority":[0,{"threshold":1,"keys":[{"key":"EOS6tw3AqqVUsCbchYRmxkPLqGct3vC63cEzKgVzLFcLionoY8YLQ","weight":1}]}]},{"producer_name":"iliketurtles","authority":[0,{"threshold":1,"keys":[{"key":"EOS6itYvNZwhqS7cLion3xp3rLJNJAvKKegxeS7guvbBxG1XX5uwz","weight":1}]}]},{"producer_name":"ivote4eosusa","authority":[0,{"threshold":1,"keys":[{"key":"EOS6GXEcfsGD3z3jQ7SZfGZ26UJLabhGc7DtqRLMCMgfcYQzZSoJX","weight":1}]}]},{"producer_name":"jumpingfrogs","authority":[0,{"threshold":1,"keys":[{"key":"EOS7oVWG413cLioNG7RU5Kv7NrPZovAdRSP6GZEG4LFUDWkgwNXHW","weight":1}]}]},{"producer_name":"lioninjungle","authority":[0,{"threshold":1,"keys":[{"key":"EOS6f8CLioNsbv8kCcLbYBpGgMyAsiKvFQJR5SAqcqWWCc5KQVFjx","weight":1}]}]},{"producer_name":"littlerabbit","authority":[0,{"threshold":1,"keys":[{"key":"EOS65orCLioNFkVT5uDF7J63bNUk97oF8T83iWfuvbSKWYUUq9EWd","weight":1}]}]},{"producer_name":"ohtigertiger","authority":[0,{"threshold":1,"keys":[{"key":"EOS7tigERwXDRuHsok212UDToxFS1joUhAxzvDUhRof8NjuvwtoHX","weight":1}]}]},{"producer_name":"proudrooster","authority":[0,{"threshold":1,"keys":[{"key":"EOS5qBd3T6nmLRsuACLion346Ue8UkCwvsoS5f3EDC1jwbrEiBDMX","weight":1}]}]},{"producer_name":"pythoncolors","authority":[0,{"threshold":1,"keys":[{"key":"EOS8R7GB5CLionUEy8FgGksGAGtc2cbcQWgty3MTAgzJvGTmtqPLz","weight":1}]}]},{"producer_name":"soaringeagle","authority":[0,{"threshold":1,"keys":[{"key":"EOS6iuBqJKqSK82QYCGuM96gduQpQG8xJsPDU1CLionPMGn2bT4Yn","weight":1}]}]},{"producer_name":"spideronaweb","authority":[0,{"threshold":1,"keys":[{"key":"EOS6M4CYEDt3JDKS6nsxMnUcdCLioNcbyEzeAwZsQmDcoJCgaNHT8","weight":1}]}]},{"producer_name":"ssssssssnake","authority":[0,{"threshold":1,"keys":[{"key":"EOS8SDhZ5CLioNLie9mb7kDu1gHfDXLwTvYBSxR1ccYSJERvutLqG","weight":1}]}]},{"producer_name":"zombiezombie","authority":[0,{"threshold":1,"keys":[{"key":"EOS7GQpG7KWgw7FaFDnkua1LadP71nF1kVqAXZ5uD8apE3gUoCxX4","weight":1}]}]}]}
info  2024-07-31T18:16:10.658 nodeos    controller.cpp:3502           log_applied          ] Received block 7864c240497a1fd4... #156849 @ 2024-07-31T18:16:11.000 signed by ssssssssnake [trxs: 0, lib: 156847, net: 0, cpu: 1, elapsed: 161, time: 701, latency: -341 ms]
info  2024-07-31T18:16:11.119 nodeos    controller.cpp:3502           log_applied          ] Received block 70c81d9b8fffd82c... #156850 @ 2024-07-31T18:16:11.500 signed by ssssssssnake [trxs: 0, lib: 156848, net: 0, cpu: 1, elapsed: 45, time: 174, latency: -380 ms]
info  2024-07-31T18:16:12.033 nodeos    controller.cpp:3502           log_applied          ] Received block d7abb1b03a8dd687... #156851 @ 2024-07-31T18:16:12.000 signed by thebluewhale [trxs: 0, lib: 156849, net: 0, cpu: 1, elapsed: 52, time: 198, latency: 33 ms]
```

- Finalizer does not start voting
```
warn  2024-07-31T18:16:12.500 nodeos    producer_plugin.cpp:639       log_missing_votes    ] Local finalizer ivote4eosusa did not vote on block 156852 : 66eb9e2f773cb4b4
```

### PR DESCRIPTION
**Pull request by heifner**
If running without a block log or with a truncated block log, it is possible that trying to retrieve a block by number will fail because the block is not available in the block log. Modify on-fork check on first handshake to allow for the block not to be found. Also allow for block not to be found on sync check in case LIB moves during sync check.

Resolves #456

### CODE REVIEW

File: plugins/net_plugin/net_plugin.cpp [hunk 1]
```diff
@@ -2343,11 +2343,14 @@ namespace eosio {
...
+         bool on_fork = false;
          try {
             controller& cc = my_impl->chain_plug->chain();
-            on_fork = cc.fork_block_id_for_num( msg.fork_head_num ) != msg.fork_head_id; // thread-safe
-         } catch( ... ) {}
+            std::optional<block_id_type> fork_head_id = cc.fork_block_id_for_num( msg.fork_head_num ); // thread-safe
+            if (fork_head_id) { // possible for LIB to move and fork_head_num not be found if running with no block-log
+               on_fork = fork_head_id != msg.fork_head_id;
+            }
+         } catch( ... ) { on_fork = true; }
```
Comment (greg7mdp) [inline plugins/net_plugin/net_plugin.cpp:2353]: Why set `on_fork` to true in case of exception?

File: plugins/net_plugin/net_plugin.cpp [hunk 2]
```diff
@@ -2343,11 +2343,14 @@ namespace eosio {
...
          if( on_fork ) {
             request_message req;
```
Comment (greg7mdp) [inline plugins/net_plugin/net_plugin.cpp:2355]: Should we add a warning log here?

File: plugins/net_plugin/net_plugin.cpp [hunk 3]
```diff
@@ -3518,9 +3521,11 @@ namespace eosio {
...
                if (!peer_lib_id) {
+                  // can be not found if running with a truncated block log
                   peer_dlog( this, "peer last irreversible block ${pl} is unknown", ("pl", peer_lib) );
+               } else {
+                  on_fork = msg.last_irreversible_block_id != peer_lib_id;
                }
-               on_fork = (msg.last_irreversible_block_id != peer_lib_id);
             } catch( ... ) {
                peer_wlog( this, "caught an exception getting block id for ${pl}", ("pl", peer_lib) );
                on_fork = true;
```
Comment (greg7mdp) [inline plugins/net_plugin/net_plugin.cpp:3531]: Should we set `on_fork = true;` here?

File: plugins/net_plugin/net_plugin.cpp (hunk 1 above)
Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp:2353]: This should never throw an exception. But previously an exception meant not found, so yeah probably should just stick with `false`.

File: plugins/net_plugin/net_plugin.cpp (hunk 2 above)
Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp:2355]: No this is a micro fork not a fork with diff LIB. I can add a debug level log.

File: plugins/net_plugin/net_plugin.cpp [hunk 4]
```diff
@@ -3518,9 +3521,11 @@ namespace eosio {
                controller& cc = my_impl->chain_plug->chain();
                std::optional<block_id_type> peer_lib_id = cc.fork_block_id_for_num( peer_lib ); // thread-safe
                if (!peer_lib_id) {
+                  // can be not found if running with a truncated block log
                   peer_dlog( this, "peer last irreversible block ${pl} is unknown", ("pl", peer_lib) );
```
Comment (linh2931) [inline plugins/net_plugin/net_plugin.cpp:3525]: Should this be an info level log?

Comment (heifner) [reply plugins/net_plugin/net_plugin.cpp:3525]: I don't think so, if running without a block log you would get that on every connection.

**Review by linh2931 — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]
