### PR TITLE
Use correct finalizer_policy for logging

### LINKED ISSUE #103: log_missing_votes assert failure
https://github.com/AntelopeIO/spring/actions/runs/8917266914/job/24490261804?pr=99#step:4:1872

The failure was caused by
`nodeos: /__w/spring/spring/plugins/producer_plugin/producer_plugin.cpp:645: void eosio::producer_plugin_impl::                   log_missing_votes(const signed_block_ptr&, const block_id_type&, const finalizer_policy_ptr&, const eosio::chain::               valid_quorum_certificate&): Assertion 'votes.size() == finalizers.size()' failed.`

Looks like the assert of `votes.size() == finalizers.size()` is too strong. Should the sizes be always the same?

Right before the failure, active finalizer policy changed. Is `chain.head_active_finalizer_policy()` https://github.com/AntelopeIO/spring/blob/a3fa40ef0974fc2fb5c5bfd70abaf9b32c9b5c02/plugins/producer_plugin/producer_plugin.cpp#L710 a correct one?

`info  2024-05-02T01:40:27.205 nodeos    block_header_state.cpp:198    finish_next          ] New finalizer policy becoming       active in block 00000094dca958564d1e292a08304b3435f68f8c80cbfafe5eada68005ac3d08: {"generation":2,"threshold":4,"finalizers":    [{"description":"finalizer #1","weight":1,"public_key":                                                                          "PUB_BLS_9vqjUfNSWu1EeycAit5GmmcoEICNIYJhFOu1lQgb57FPebfRZ5OzHuCrxDDQNm0L15DKKwD4vKs1h-Sop7h2QJkNoQGIsLOuFlGVlIlVvB3-            Q_TdO_HLen_alXtU4F0LGYfDRg"},{"description":"finalizer #2","weight":1,"public_key":"PUB_BLS_Awr-                                 VUIZ0SEofZQYPc5N0rWwNQid5eBmverhoacGSqVozAa6Wh9COpqCOJoD5uEJ5TuJUG3aCVRblGjFZDD1zweLISsDU0D5rRkMQ5JiUZLkRH3KAgageTirQIgI9c8MI5X7qw"},{"description":"finalizer #3","weight":1,"public_key":"PUB_BLS_d_moeh6iA9A5nbOZWmf6IcOyN4sIPYuZhUCdzvJA33N78sayp7couj5-ZdO-  SQYV1P0oPRbVS2tv7TEdFNCsnAurnJ86Wor1U4mJg1QIpgJkZ5meEt3JlsriQ6umumMTkN6wNg"},{"description":"finalizer #4","weight":1,           "public_key":"PUB_BLS_SSoZug-A9AlfdHVqHLjsIiFpas8KEPr-vA5RVrhyotM8JD-                                                            HM4sN0KMF3Ym7cXMA4wtbgbwHIMg8AcmRfgGph4vkpMgfpd6AqaRuWFmaMvbkmUwl7Q3QgFhX56ccldQJrCCQWw"},{"description":"finalizer #5","weight":1,"public_key":"PUB_BLS_qVbh4IjYZpRGo8U_0spBUM-u-                                                                                r_G0fMo4MzLZRsKWmm5uyeQTp74YFaMN9IDWPoVVT5rj_Tw1gvps6K9_OZ6sabkJJzug3uGfjA6qiaLbLh5Fnafwv-nVgzzzBlU2kwRrcHc8Q"}]}                debug 2024-05-02T01:40:27.207 nodeos    block_state.cpp:53            block_state          ] integrate qc {"block_num":147,      "is_strong_qc":true} into block 148 00000094dca958564d1e292a08304b3435f68f8c80cbfafe5eada68005ac3d08`

### PR DESCRIPTION
**Pull request by heifner**
The active finalizer policy associated with the qc should be used when logging the qc, not the head block finalizer policy.

Resolves #103

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]

File: plugins/producer_plugin/producer_plugin.cpp [hunk 1]
```diff
@@ -707,8 +707,8 @@ class producer_plugin_impl : public std::enable_shared_from_this<producer_plugin
       }
       if (vote_logger.is_enabled(fc::log_level::info) || _update_vote_block_metrics) {
          if (block->contains_extension(quorum_certificate_extension::extension_id())) {
-            if (const auto& active_finalizers = chain.head_active_finalizer_policy()) {
-               const auto& qc_ext = block->extract_extension<quorum_certificate_extension>();
+            const auto& qc_ext = block->extract_extension<quorum_certificate_extension>();
+            if (const auto& active_finalizers = chain.active_finalizer_policy(qc_ext.qc.block_num)) {
```
Comment (greg7mdp) [inline plugins/producer_plugin/producer_plugin.cpp:711]: It doesn't seem right to assume that `block` is on the head branch. We should probably use the branch that `block` is on, and fetch the `qc_ext.qc.block_num`  from that branch.

**Review by greg7mdp — CHANGES_REQUESTED** [review]

File: plugins/producer_plugin/producer_plugin.cpp (hunk 1 above)
Comment (heifner) [reply plugins/producer_plugin/producer_plugin.cpp:711]: `accepted_block` signal is on the head. We do have the id handy to find the correct branch, probably safer to do it that way.

**Review by greg7mdp — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: INTERNALS
summary: Use the correct finalizer policy when logging.
Note:end
