### PR TITLE
[1.0.4 -> main] Fix fetch block with no block log

### LINKED ISSUE #1052: Invalid warn message on startup
```
warn  2024-12-05T13:45:22.176 nodeos    producer_plugin.cpp:1617      plugin_startup       ] Legacy consensus active. Accepting speculative transaction execution not recommended in read-mode=irreversible
```

Savanna was active at startup. The following is not returning the root of the fork db.
https://github.com/AntelopeIO/spring/blob/631fed0498bb87d7eba266aa1552f4d4bf95e0e2/plugins/producer_plugin/producer_plugin.cpp#L1594-L1595

### PR DESCRIPTION
**Pull request by heifner**
The startup of `producer_plugin` uses `fetch_block_by_number` to prime `on_irreversible_block` with LIB.
https://github.com/AntelopeIO/spring/blob/838e885908aaa1f19aff9aaf4433a6f7904e86cb/plugins/producer_plugin/producer_plugin.cpp#L1612-L1613

When running without a block log, `fetch_block_by_number` always returned `nullptr` for LIB.

Update `fetch_block_by_number` and `fetch_block_by_id` to find LIB in fork database.

Merges `release/1.0` into `main` including #1059. Adds commit 5c8ea40c65c12e1b4ff5466fc1d6710b5e4f3e56.

Resolves #1052

### CODE REVIEW

File: plugins/producer_plugin/producer_plugin.cpp [hunk 1]
```diff
@@ -1609,14 +1609,14 @@ void producer_plugin_impl::plugin_startup() {
       const auto fork_db_root     = chain.fetch_block_by_number(fork_db_root_num);
       if (fork_db_root) {
          on_irreversible_block(fork_db_root);
+
+         if (!_is_savanna_active && irreversible_mode() && chain_plug->accept_transactions()) {
+            wlog("Legacy consensus active. Accepting speculative transaction execution not recommended in read-mode=irreversible");
+         }
```
Comment (linh2931) [inline plugins/producer_plugin/producer_plugin.cpp:1615]: I guess it is OK this is not in rel 1.0.

**Review by linh2931 — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
category: System Stability
component: Internal
summary: Fix fetch block with no block log. This removes unneeded warning by fixing underlying issue.
Note:end
