### PR TITLE
Write chain_head after vote threads have stopped

### LINKED ISSUE #369: test failure: `nodeos_retry_transaction_if_lr_test`
See [here](https://github.com/AntelopeIO/spring/actions/runs/9964086157/job/27532098443)

```
Total Test time (real) = 224.66 sec
1/1 Test #2162: nodeos_retry_transaction_if_lr_test ...***Failed  226.66 sec
```

### PR DESCRIPTION
**Pull request by heifner**
Make sure vote_processor threads have stopped before writing out the `chain_head` to avoid modifications to the `block_state` while writing. Note `fork_db` was already being written out after the vote processor threads were shutdown.

Resolves #369

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]

File: libraries/chain/controller.cpp [hunk 1]
```diff
@@ -946,6 +946,8 @@ struct controller_impl {
    authorization_manager           authorization;
    protocol_feature_manager        protocol_features;
    controller::config              conf;
+   // write out chain_head after vote_processor has stopped to avoid concurrent access while writing
+   fc::scoped_exit<std::function<void()>> write_chain_head = [&]() { chain_head.write(conf.state_dir / config::chain_head_filename); };
```
Comment (greg7mdp) [inline libraries/chain/controller.cpp:950]: Maybe add a comment stating that this member has to come after `chain_head`, `fork_db` and `conf`.

**Review by greg7mdp — APPROVED** [review]

File: libraries/chain/controller.cpp (hunk 1 above)
Comment (greg7mdp) [reply libraries/chain/controller.cpp:950]: doesn't it depend on fork_db as well?

Comment (heifner) [reply libraries/chain/controller.cpp:950]: In what way does it depend on forkdb?

Comment (greg7mdp) [reply libraries/chain/controller.cpp:950]: I thought [this](https://github.com/AntelopeIO/spring/blob/c2cffd8d7c255e997a0565fbebf3596298f16c5b/libraries/chain/include/eosio/chain/block_handle.hpp#L44) would write the `block_state` which is stored in fork_db?

Comment (heifner) [reply libraries/chain/controller.cpp:950]: The block_state is stored in a shared_ptr that is referenced in forkdb. But the forkdb is not modifying the block state.

Comment (greg7mdp) [reply libraries/chain/controller.cpp:950]: I don't know what I was thinking. Thanks!

**Comment by ericpassmore** [comment]
Note:start
group: STABILITY
category: INTERNALS
summary: Write out chain_head after vote_processor threads have stopped.
Note:end
