### PR TITLE
[1.0] Add test case to demonstrate the weak masking issue

### LINKED ISSUE #544: Add test case to demonstrate the weak masking issue
The weak masking issue is described in #534 .

PR #537 implements FSI changes to avoid the issue.

We need a test case which fails on a branch based off commit  https://github.com/AntelopeIO/spring/commit/7beaa2027f37a38ac8b15578598b207f30804118 , but passes on the main branch after PR #537 was merged.

### PR DESCRIPTION
**Pull request by greg7mdp**
Resolves #544.

Branch `gh_544_check`  created off commit 7beaa202 prior to PR #537 (implementing the FSI changes to avoid the issue) has the new test failing.

### CODE REVIEW

File: unittests/savanna_cluster.hpp [hunk 1]
```diff
@@ -54,13 +91,30 @@ namespace savanna_cluster {
...
-      bool                    pushing_a_block {false };
+      size_t node_idx;
+      bool   pushing_a_block{false};
 
       std::function<void(const block_signal_params&)> accepted_block_cb;
       std::function<void(const vote_signal_params&)>  voted_block_cb;
 
    public:
+      struct vote_t {
+         vote_t() = default;
```
Comment (heifner) [inline unittests/savanna_cluster.hpp:102]: `strong` is not initialized.

File: unittests/savanna_cluster.hpp [hunk 2]
```diff
@@ -10,6 +10,43 @@
 
 #include "snapshot_suites.hpp"
 
+// ---------------------------------------------------------------------------
+// An object which assigns a value to a variable in its constructor, and resets
+// to its previous value in its destructor
+// ---------------------------------------------------------------------------
+template <class T>
+class scoped_set_value {
```
Comment (heifner) [inline unittests/savanna_cluster.hpp:18]: Consider moving to `fc` for reuse.

File: unittests/savanna_cluster.hpp [hunk 3]
```diff
@@ -54,13 +91,30 @@ namespace savanna_cluster {
...
+      size_t node_idx;
+      bool   pushing_a_block{false};
 
       std::function<void(const block_signal_params&)> accepted_block_cb;
       std::function<void(const vote_signal_params&)>  voted_block_cb;
 
    public:
+      struct vote_t {
+         vote_t() = default;
+         vote_t(const vote_message_ptr& p) : id(p->block_id), strong(p->strong) {}
```
Comment (heifner) [inline unittests/savanna_cluster.hpp:103]: `explicit`

File: unittests/savanna_cluster.hpp [hunk 4]
```diff
@@ -455,9 +508,44 @@ namespace savanna_cluster {
 
       size_t num_nodes() const { return _num_nodes; }
 
+      // Class for comparisons in BOOST_REQUIRE_EQUAL
+      // --------------------------------------------
+      struct qc_s {
+         qc_s(const signed_block_ptr& p, bool strong) : block_num(p->block_num()), strong(strong) {}
+         qc_s(const std::optional<qc_t>& qc) : block_num(qc->block_num), strong(qc->is_strong()) {}
```
Comment (heifner) [inline unittests/savanna_cluster.hpp:515]: `explicit`

**Review by heifner — CHANGES_REQUESTED** [review]

File: unittests/savanna_cluster.hpp (hunk 2 above)
Comment (greg7mdp) [reply unittests/savanna_cluster.hpp:18]: Yes, sounds good. I moved it to `fc/scoped_exit.hpp` as I don't think we need a file for every class but let me know if you think it is better to create its own file.

**Review by heifner — APPROVED** [review]

File: unittests/savanna_cluster.hpp (hunk 2 above)
Comment (greg7mdp) [reply unittests/savanna_cluster.hpp]: I  feel like renaming `scoped_exit.hpp` to `scoped_utils.hpp`. What do you think?

Comment (heifner) [reply unittests/savanna_cluster.hpp]: I think it is fine as is.

**Comment by ericpassmore** [comment]
Note:start
group: STABILITY
category: TEST
summary: Add test case to demonstrate weak masking issue.
Note:end

**Comment by ericpassmore** [comment]
nice ascii graph in unittests/savanna_misc_tests.cpp

File: unittests/savanna_cluster.hpp [hunk 5]
```diff
@@ -455,9 +471,44 @@ namespace savanna_cluster {
...
+         if (b->contains_extension(quorum_certificate_extension::extension_id()))
+             return b->extract_extension<quorum_certificate_extension>().qc;
+         return {};
+      }
+
+      // debugging utilities
+      // -------------------
+      void print(const char* name, const signed_block_ptr& b) const {
+         if (_debug_mode)
+            std::cout << name << " ts = " << b->timestamp.slot << ", id = " << b->calculate_id().str().substr(8, 16)
```
Comment (linh2931) [inline unittests/savanna_cluster.hpp:504]: As this is in debug mode, you can just print out the whole ID.

File: unittests/savanna_misc_tests.cpp [hunk 6]
```diff
@@ -39,5 +41,112 @@ BOOST_FIXTURE_TEST_CASE(snapshot_startup_with_forkdb, savanna_cluster::cluster_t
...
+                     ^
+                     |                    +-----+
+D produces           +--------------------| b2  |
+                                     S    +-----+
+
+*/
+BOOST_FIXTURE_TEST_CASE(weak_masking_issue, savanna_cluster::cluster_t) try {
+   auto& A=_nodes[0]; auto& B=_nodes[1]; auto& C=_nodes[2]; auto& D=_nodes[3];
+   using vote_t = savanna_cluster::node_t::vote_t;
+   //_debug_mode = true;
```
Comment (linh2931) [inline unittests/savanna_misc_tests.cpp:65]: Remove this commented out line.

**Review by linh2931 — APPROVED** [review]

File: unittests/savanna_cluster.hpp (hunk 5 above)
Comment (heifner) [reply unittests/savanna_cluster.hpp:504]: I missed this `cout`, use `ilog` and then you can enable via `unittest -- --verbose` and you don't need the `_debug_mode`.

Comment (greg7mdp) [reply unittests/savanna_cluster.hpp:504]: I actually like this better because I print only what is relevant for the test.

File: unittests/savanna_misc_tests.cpp (hunk 6 above)
Comment (greg7mdp) [reply unittests/savanna_misc_tests.cpp:65]: I like having it here personally.
