### PR TITLE
Do not unwind validated blocks on interrupt

### LINKED ISSUE #1022: 1.1 attempt to pop beyond last irreversible block
Noticed the following warning.
```
^Cinfo  2024-11-08T13:04:40.741 nodeos    main.cpp:193                  operator()           ] appbase quit called
info  2024-11-08T13:04:40.741 nodeos    controller.cpp:4536           interrupt_transactio ] Interrupting apply block
info  2024-11-08T13:04:40.742 nodeos    controller.cpp:3820           apply_block          ] Interrupt of trx id: e6175b672d97e3f0110d70466c6c65d27f8cd2a5fc344d7efbe5a3e7c59090f5
info  2024-11-08T13:04:40.742 nodeos    controller.cpp:4464           operator()           ] interrupt while applying block 398678346 : 17c3594aee3d06f3d51e01c5afbe6c18d3216298d870cdfb9c79264cdcb6049d
warn  2024-11-08T13:04:40.754 nodeos    controller.cpp:4385           apply_blocks         ] 3030000 block_validate_exception: Block exception
attempt to pop beyond last irreversible block
    {}
    nodeos  controller.cpp:1165 pop_block
```

When a transaction is interrutped via `ctrl-c`, the trx and block are aborted. The block is removed from the forkdb and all of its decendants.

- Do we want to remove the block and its descendants from the forkdb? If syncing then those blocks have to be re-requested on startup. However, if the block is a poison block, then leaving it in the forkdb means the node will be in the same situation on restart. Seems safest and easiest to just remove it and its descendants.

### PR DESCRIPTION
**Pull request by heifner**
Noticed the following warning.
```
^Cinfo  2024-11-08T13:04:40.741 nodeos    main.cpp:193                  operator()           ] appbase quit called
info  2024-11-08T13:04:40.741 nodeos    controller.cpp:4536           interrupt_transactio ] Interrupting apply block
info  2024-11-08T13:04:40.742 nodeos    controller.cpp:3820           apply_block          ] Interrupt of trx id: e6175b672d97e3f0110d70466c6c65d27f8cd2a5fc344d7efbe5a3e7c59090f5
info  2024-11-08T13:04:40.742 nodeos    controller.cpp:4464           operator()           ] interrupt while applying block 398678346 : 17c3594aee3d06f3d51e01c5afbe6c18d3216298d870cdfb9c79264cdcb6049d
warn  2024-11-08T13:04:40.754 nodeos    controller.cpp:4385           apply_blocks         ] 3030000 block_validate_exception: Block exception
attempt to pop beyond last irreversible block
    {}
    nodeos  controller.cpp:1165 pop_block
```

When interrupting a transaction via `ctrl-c`, do not attempt to unwind the branch. Also no need to attempt to discard a bad fork if not actually switching forks.

Related to #993
Resolves #1022

### CODE REVIEW

File: libraries/chain/controller.cpp [hunk 1]
```diff
@@ -4478,18 +4479,20 @@ struct controller_impl {
...
 
-               // pop all blocks from the bad fork, discarding their transactions
-               // ritr base is a forward itr to the last block successfully applied
-               auto applied_itr = ritr.base();
-               for( auto itr = applied_itr; itr != new_head_branch.end(); ++itr ) {
-                  pop_block();
-               }
-               EOS_ASSERT( !switch_fork || chain_head.id() == old_head_branch.back()->header.previous, fork_database_exception,
-                           "loss of sync between fork_db and chainbase during fork switch reversal" ); // _should_ never fail
+               if (switch_fork) {
```
Comment (greg7mdp) [inline libraries/chain/controller.cpp:4482]: Why this `if (switch_fork)`? The comment at line 4479 makes sense to me that if a block throws, we should not keep its descendants.

**Review by greg7mdp — APPROVED** [review]

**Review by linh2931 — APPROVED** [review]

**Review by greg7mdp — APPROVED** [review]

**Comment by ericpassmore** [comment]
Note:start
category: System Stability
component: Internal
summary: Do not unwind validated blocks on interrupt.
Note:end
