### PR TITLE
[1.1.4] Correctly identify snapshot as forked out

### LINKED ISSUE #1355: Pending snapshot incorrectly identified as irreversible
Test failure: disaster_recovery

`release/1.1` branch

https://github.com/AntelopeIO/spring/actions/runs/14408005992/job/40409842148

node_00 before shutdown
```
info  2025-04-11T17:01:48.019 nodeos    controller.cpp:4523           operator()           ] successfully switched fork to new head 000000885c00cdbd3aebc163f40cec1a9e35663b036e5fa801a69274627d4ba1, removed {136:00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b}, applied {136:000000885c00cdbd3aebc163f40cec1a9e35663b036e5fa801a69274627d4ba1}
```

node_00 snapshot block didn't become irreversible. Returned block id of non-irreversible block 136.
```
info  2025-04-11T17:01:48.965 nodeos    pending_snapshot.hpp:54       finalize             ] Snapshot created at block 136 available at /__w/spring/spring/build/TestLogs/disaster_recovery9/node_00/snapshots/snapshot-00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b.bin
debug 2025-04-11T17:01:48.981 http-1    beast_http_session.hpp:481    send_response        ] Response: localhost:8888 HTTP/1.1 201 Created  Connection: close  Server: nodeos/v1.1.3  Content-Type: application/json  Content-Length: 328    {"head_block_id":"00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b","head_block_num":136,"head_block_time":"2025-04-11T17:01:47.500","version":8,"snapshot_name":"/__w/spring/spring/build/TestLogs/disaster_recovery9/node_00/snapshots/snapshot-00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b.bin"}
```

node_00
```
info  2025-04-11T17:02:01.045 nodeos    controller.cpp:1923           startup              ] Starting initialization from snapshot and block log 1-146, this may take a significant amount of time
info  2025-04-11T17:02:01.056 nodeos    controller.cpp:1935           startup              ] Snapshot loaded, head: 136 : 00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b
info  2025-04-11T17:02:01.057 nodeos    controller.cpp:1697           replay_block_log     ] existing block log, attempting to replay from 137 to 146 blocks
warn  2025-04-11T17:02:01.057 nodeos    controller.cpp:4371           replay_irreversible_ ] 3030001 unlinkable_block_exception: Unlinkable block
previous mismatch 000000885c00cdbd3aebc163f40cec1a9e35663b036e5fa801a69274627d4ba1 != 00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b
    {"p":"000000885c00cdbd3aebc163f40cec1a9e35663b036e5fa801a69274627d4ba1","id":"00000088d88fa3fcd93a0bf548545b6db55e2e1a785ea46827b0fbb1f7c4213b"}
    nodeos  block_header_state.cpp:494 next
```

### PR DESCRIPTION
**Pull request by heifner**
Snapshot was verifying that a block was irreversible by `chain.fetch_block_by_id(block_id)`. However this was checked on the `irreversible_block` signal which is signaled before forks are pruned from the fork database. Therefore, it was possible to find a non-irreversible block for a block_id that was non-irreversible but that had a block_num <= LIB.

Not sure it is worth the complexity to support lib_num < block_num, but kept the existing functionality. Looks like this really only handles the rare cases of starting from a snapshot and creating a snapshot on HEAD. Or switching from IRREVERSIBLE to HEAD mode with a snapshot scheduled on an irreversible block that becomes irreversible. Even in those cases this could still potentially fail if running without a block log.

The snapshot scheduler previously would not generate a snapshot for a forked out block. For example, if a snapshot was scheduled for block 7, but 7 was forked out, then it would not generate a snapshot on the canonical 7 block. With this PR, the scheduler will generate two snapshots for block 7 and throw the first one away.

Resolves #1355

### CODE REVIEW

**Review by greg7mdp — APPROVED** [review]

File: libraries/chain/include/eosio/chain/pending_snapshot.hpp [hunk 1]
```diff
@@ -33,9 +33,16 @@ class pending_snapshot {
...
+      auto lib_num = chain::block_header::num_from_id(lib_id);
+      auto block_num = chain::block_header::num_from_id(block_id);
+
+      EOS_ASSERT(lib_num >= block_num, chain::snapshot_finalization_exception,
+                 "finalize called for non-irreversible block ${bn}:${bid}", ("bn", block_num)("bid", block_id));
+
+      // finalize called before forkdb is pruned of non-irreversible blocks, so this can find a non-irreversible block
       auto block_ptr = chain.fetch_block_by_id(block_id);
-      auto in_chain = (bool) block_ptr;
+      auto in_chain = !!block_ptr && (lib_num > block_num || lib_id == block_id);
```
Comment (spoonincode) [inline libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: I'm not immediately understanding the rationale for this check and the assert above. What conditions mean that a simple `bool in_chain = lib_id == block_id` isn't sufficient? I guess tihs is what your second paragraph is getting at.

Comment (heifner) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: My thoughts exactly. The more I think about this, I think I should simplify this instead of leaving this "dead" code.

Comment (spoonincode) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: I wonder if there might be some corner case where where you start from a snapshot in HEAD mode and request a snapshot before receiving any new blocks. Maybe you'll never get on on_reverisble for that initial block since it was already irreversible?

Comment (heifner) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: Hmm, that does seem possible. I think we could just EOS_ASSERT on that with a message that LIB not signaled. You should have a snapshot for that HEAD since that is what you started with to begin with.  Might be possible to miss it as well by switching from IRREVERSIBLE to HEAD and the producer plugin on active when the blocks are applied. Again an EOS_ASSERT to the caller that LIB was missed seems like an ok fall-back for those cases.

Comment (spoonincode) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: In that case maybe instead of the `EOS_ASSERT` here, the logic that iterates through the pending snapshots could be modified,
https://github.com/AntelopeIO/spring/blob/17b468887e2db1301bf3892ba1caa72e21f2ebc1/libraries/chain/snapshot_scheduler.cpp#L52
It's the `<=` that causes this weirdness.

So in this loop we can then check if it's `<` (only will occur for these startup quirks afaict so far) then we can skip calling `finialize()` altogether (maybe still log an error :woman_shrugging:), and then if it's `==` the logic becomes a simple `bool in_chain = lib_id == block_id` I think?

Just an idea.

Comment (spoonincode) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: oh we can't do that since it's finalize that removes the pending snapshot. womp womp nevermind

Comment (heifner) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:45]: For the cases outlined, I guess best to just leave it as is.

**Review by greg7mdp — APPROVED** [review]

File: libraries/chain/include/eosio/chain/pending_snapshot.hpp [hunk 2]
```diff
@@ -33,9 +33,16 @@ class pending_snapshot {
       return snapshots_dir / fc::format_string(".incomplete-snapshot-${id}.bin", fc::mutable_variant_object()("id", block_id));
    }
 
-   T finalize(const chain::controller& chain) const {
+   T finalize(const block_id_type& lib_id, const chain::controller& chain) const {
+      auto lib_num = chain::block_header::num_from_id(lib_id);
+      auto block_num = chain::block_header::num_from_id(block_id);
+
+      EOS_ASSERT(lib_num >= block_num, chain::snapshot_finalization_exception,
```
Comment (spoonincode) [inline libraries/chain/include/eosio/chain/pending_snapshot.hpp:40]: How does this ever occur -- why not assert()?

Comment (heifner) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp:40]: It could be an assert() I believe. I'll update.

File: libraries/chain/include/eosio/chain/pending_snapshot.hpp [hunk 3]
```diff
@@ -33,9 +33,15 @@ class pending_snapshot {
...
 
-   T finalize(const chain::controller& chain) const {
+   T finalize(const block_id_type& lib_id, const chain::controller& chain) const {
+      auto lib_num = chain::block_header::num_from_id(lib_id);
+      auto block_num = chain::block_header::num_from_id(block_id);
+
+      assert(lib_num >= block_num);
+
+      // finalize called before forkdb is pruned of non-irreversible blocks, so this can find a non-irreversible block
       auto block_ptr = chain.fetch_block_by_id(block_id);
```
Comment (spoonincode) [inline libraries/chain/include/eosio/chain/pending_snapshot.hpp:43]: imo it'd be nice to remove `block_ptr` since it and the new comment above are now red herrings on how this works -- the check for `block_ptr` for `in_chain` doesn't really have anything to do with _whether it's in chain_, it's just there to guard against bad usage of it later on. A more useful comment would be why `lib_num > block_num` is sufficient for being considered in chain. (what we discussed here about snapshots immediately at start)

But it's not easy to remove due to `block_ptr->timestamp` below.

Comment (heifner) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp]: I changed it to store timestamp so it doesn't need to be retrieved. Also improved the comments.

Comment (spoonincode) [reply libraries/chain/include/eosio/chain/pending_snapshot.hpp]: lgtm :shipit:

**Review by greg7mdp — APPROVED** [review]
