### PR TITLE
[1.2.0-rc3] Test: Relax hard thread test

### LINKED ISSUE #1502: Test failure: custom_appbase_tests
https://github.com/AntelopeIO/spring/actions/runs/14861955944/job/41729950570

```
  21/2107 Test    #8: custom_appbase_test ................................***Failed    0.04 sec
Running 8 test cases...
../libraries/custom_appbase/tests/custom_appbase_tests.cpp(582): error: in "custom_appbase_tests/execute_many_from_read_only_and_read_exclusive_queues": check run_on_main > 0 has failed

*** 1 failure is detected in the test module "custom_appbase_tests"
```

### PR DESCRIPTION
**Pull request by heifner**
Do not require every thread to run a task in test. In practice sometimes a thread doesn't actually run a task. There is nothing that would guarantee every thread runs at least one task, so don't require it.

Resolves #1502

### CODE REVIEW

File: libraries/custom_appbase/tests/custom_appbase_tests.cpp [hunk 1]
```diff
@@ -576,10 +576,11 @@ BOOST_AUTO_TEST_CASE( execute_many_from_read_only_and_read_exclusive_queues ) {
    const auto run_on_main = std::count_if(rslts.cbegin(), rslts.cend(), [&](const auto& v){ return v == app->executor().get_main_thread_id(); });
 
    BOOST_REQUIRE_EQUAL(run_on_1+run_on_2+run_on_3+run_on_main, num_expected);
-   BOOST_CHECK(run_on_1 > 0);
-   BOOST_CHECK(run_on_2 > 0);
-   BOOST_CHECK(run_on_3 > 0);
-   BOOST_CHECK(run_on_main > 0);
+   // We expect at least one to run on every thread including main, but nothing guarantees that
```
Comment (linh2931) [inline libraries/custom_appbase/tests/custom_appbase_tests.cpp:579]: Because we already have `BOOST_REQUIRE_EQUAL(run_on_1+run_on_2+run_on_3+run_on_main, num_expected);`, can we just remove those `BOOST_WARN` checks?

Comment (linh2931) [reply libraries/custom_appbase/tests/custom_appbase_tests.cpp:579]: But put a comment there.

**Review by greg7mdp — APPROVED** [review]

File: libraries/custom_appbase/tests/custom_appbase_tests.cpp (hunk 1 above)
Comment (heifner) [reply libraries/custom_appbase/tests/custom_appbase_tests.cpp:579]: I'm ok with removing them. @greg7mdp what do you think?

Comment (greg7mdp) [reply libraries/custom_appbase/tests/custom_appbase_tests.cpp:579]: Sure, let's remove them.

Comment (heifner) [reply libraries/custom_appbase/tests/custom_appbase_tests.cpp]: https://github.com/AntelopeIO/spring/pull/1530/commits/232376eded26b07d8fa595dbf01d83f79acbf4f5

Comment (linh2931) [reply libraries/custom_appbase/tests/custom_appbase_tests.cpp]: Thanks! Very clean!

**Review by linh2931 — APPROVED** [review]
