### PR TITLE
[1.0] Update max-reversible-blocks to only enforce savanna blocks

### LINKED ISSUE #579: max-reversible-blocks syncing old blocks
Matthew Darwin
> Trying to sync kylin from genesis fails with Exceeded max reversible blocks allowed, fork db size 3634 >= max-reversible-blocks 3600.  There is a period at the start of the chain where LIB fails to move forward.   
> 
> Should max-reversible-blocks be applied on p2p sync ancient blocks?

> LIB drifts by at least 65K blocks.

### PR DESCRIPTION
**Pull request by heifner**
Update the `max-reversible-blocks` option to only be enforced for blocks after the Savanna transition.

Resolves #579

### CODE REVIEW

**Review by arhag — APPROVED** [review]

File: libraries/chain/controller.cpp [hunk 1]
```diff
@@ -1117,6 +1117,13 @@ struct controller_impl {
       return prev->block_num();
    }
 
+   // returns 0 for legacy
```
Comment (greg7mdp) [inline libraries/chain/controller.cpp:1120]: I wonder if this is guaranteed by the standard?

**Review by greg7mdp — APPROVED** [review]

File: libraries/chain/controller.cpp (hunk 1 above)
Comment (heifner) [reply libraries/chain/controller.cpp:1120]: Yes, https://en.cppreference.com/w/cpp/language/zero_initialization
